# Copyright (c) 2021 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

type: "//rec"
required:
  description: "//str"
  task_type: "//str"
  files:
    type: "//arr"
    contents:
      type: "//rec"
      required:
        name: "//str"
        size: "//int"
        checksum:
          type: "//any"
          of:
            - "//str"
            - type: "//rec"
              required:
                $type: "//str"
                value: "//str"
        source:
          type: "//any"
          of:
            - "//str"
            - type: "//rec"
              required:
                $type: "//str"
                id: "//str"
      optional:
        original_source:
          type: "//any"
          of:
            - "//str"
            - type: "//rec"
              required:
                $type: "//str"
                id: "//str"
  framework: "//str"
  license: "//str"
optional:
  postprocessing:
    type: "//arr"
    contents:
      type: "//rec"
      required:
        $type: "//str"
        file: "//str"
      optional:
        pattern: "//str"
        replacement: "//str"
        format: "//str"
        count: "//int"
  model_optimizer_args:
    type: "//arr"
    contents: "//str"
  conversion_to_onnx_args:
    type: "//arr"
    contents: "//str"
  quantizable: "//bool"
  quantized: "//str"
