models:
  - name: face-detection-retail-0004

    launchers:
      - framework: dlsdk
        device: CPU
        model: face-detection-retail-0004/FP32/face-detection-retail-0004.xml
        weights: face-detection-retail-0004/FP32/face-detection-retail-0004.bin
        adapter: ssd
        cpu_extensions: libcpu_extension_avx2.so

      - framework: dlsdk
        device: GPU
        model: face-detection-retail-0004/FP32/face-detection-retail-0004.xml
        weights: face-detection-retail-0004/FP32/face-detection-retail-0004.bin
        adapter: ssd

      - framework: dlsdk
        device: GPU
        model: face-detection-retail-0004/FP16/face-detection-retail-0004.xml
        weights: face-detection-retail-0004/FP16/face-detection-retail-0004.bin
        adapter: ssd

      - framework: dlsdk
        device: HETERO:FPGA,CPU
        model: face-detection-retail-0004/FP32/face-detection-retail-0004.xml
        weights: face-detection-retail-0004/FP32/face-detection-retail-0004.bin
        adapter: ssd
        cpu_extensions: libcpu_extension_avx2.so
        bitstream: 4-0_A10DK_FP16_MobileNet_SqueezeNet_VGG_ELU.aocx

      - framework: dlsdk
        device: HETERO:FPGA,CPU
        model: face-detection-retail-0004/FP32/face-detection-retail-0004.xml
        weights: face-detection-retail-0004/FP32/face-detection-retail-0004.bin
        adapter: ssd
        cpu_extensions: libcpu_extension_avx2.so
        bitstream: 4-0_A10DK_FP11_MobileNet.aocx

    datasets:
      - name: wider

        data_source: WIDER_val/images
        annotation: wider.pickle
        dataset_meta: wider.json

        preprocessing:
          - type: resize
            size: 300

        postprocessing:
          - type: resize_prediction_boxes
          - type: cast_to_int
          - type: filter
            apply_to: annotation
            height_range: 60
            is_empty: True
          - type: filter
            min_confidence: 0.00
            apply_to: prediction

        metrics:
          - type: map
            ignore_difficult: True
            include_boundaries: False
            allow_multiple_matches_per_ignored: False
            distinct_conf: False
