models:
  - name: face-detection-adas-0001

    launchers:
      - framework: dlsdk
        device: CPU
        model:   face-detection-adas-0001/FP32/face-detection-adas-0001.xml
        weights: face-detection-adas-0001/FP32/face-detection-adas-0001.bin
        adapter: ssd
        cpu_extensions: libcpu_extension_avx2.so

      - framework: dlsdk
        device: GPU
        model:   face-detection-adas-0001/FP32/face-detection-adas-0001.xml
        weights: face-detection-adas-0001/FP32/face-detection-adas-0001.bin
        adapter: ssd

      - framework: dlsdk
        device: GPU
        model:   face-detection-adas-0001/FP16/face-detection-adas-0001.xml
        weights: face-detection-adas-0001/FP16/face-detection-adas-0001.bin
        adapter: ssd

      - framework: dlsdk
        device: MYRIAD
        model:   face-detection-adas-0001/FP16/face-detection-adas-0001.xml
        weights: face-detection-adas-0001/FP16/face-detection-adas-0001.bin
        adapter: ssd

      - framework: dlsdk
        device: HETERO:FPGA,CPU
        model:   face-detection-adas-0001/FP32/face-detection-adas-0001.xml
        weights: face-detection-adas-0001/FP32/face-detection-adas-0001.bin
        adapter: ssd
        cpu_extensions: libcpu_extension_avx2.so
        bitstream: 4-0_A10DK_FP16_MobileNet_ResNet_SqueezeNet_Clamp.aocx

    datasets:
      - name: wider
        data_source: WiderFace/WIDER_val/images
        annotation: wider.pickle
        dataset_meta: wider.json

        preprocessing:
          - type: resize
            dst_width: 672
            dst_height: 384

        postprocessing:
          - type: resize_prediction_boxes
          - type: filter
            height_range: 100
            apply_to: annotation

        metrics:
          - type: map
            ignore_difficult: True
            include_boundaries: False
            allow_multiple_matches_per_ignored: True
            use_filtered_tp: True
