models:
  - name: landmarks-regression-retail-0009

    launchers:
      - framework: dlsdk
        device: CPU
        model:   landmarks-regression-retail-0009/FP32/landmarks-regression-retail-0009.xml
        weights: landmarks-regression-retail-0009/FP32/landmarks-regression-retail-0009.bin
        adapter: landmarks_regression
        cpu_extensions: libcpu_extension_avx2.so

      - framework: dlsdk
        device: GPU
        model:   landmarks-regression-retail-0009/FP32/landmarks-regression-retail-0009.xml
        weights: landmarks-regression-retail-0009/FP32/landmarks-regression-retail-0009.bin
        adapter: landmarks_regression

      - framework: dlsdk
        device: GPU
        model:   landmarks-regression-retail-0009/FP16/landmarks-regression-retail-0009.xml
        weights: landmarks-regression-retail-0009/FP16/landmarks-regression-retail-0009.bin
        adapter: landmarks_regression

      - framework: dlsdk
        device: MYRIAD
        model:   landmarks-regression-retail-0009/FP16/landmarks-regression-retail-0009.xml
        weights: landmarks-regression-retail-0009/FP16/landmarks-regression-retail-0009.bin
        adapter: landmarks_regression

    datasets:
      - name: vgg2face
        data_source: VGGFaces2/test
        annotation: landmarks_regression.pickle

        preprocessing:
          - type: crop_rect
          - type: resize
            size: 48

        postprocessing:
          - type: normalize_landmarks_points
            use_annotation_rect: True

        metrics:
          - type: per_point_normed_error
            presenter: print_vector
          - type: normed_error
