models:
  - name: person-reidentification-retail-0031

    launchers:
      - framework: dlsdk
        device: CPU
        model:   person-reidentification-retail-0031/FP32/person-reidentification-retail-0031.xml
        weights: person-reidentification-retail-0031/FP32/person-reidentification-retail-0031.bin
        adapter: reid

      - framework: dlsdk
        device: GPU
        model:   person-reidentification-retail-0031/FP32/person-reidentification-retail-0031.xml
        weights: person-reidentification-retail-0031/FP32/person-reidentification-retail-0031.bin
        adapter: reid

      - framework: dlsdk
        device: GPU
        model:   person-reidentification-retail-0031/FP16/person-reidentification-retail-0031.xml
        weights: person-reidentification-retail-0031/FP16/person-reidentification-retail-0031.bin
        adapter: reid

      - framework: dlsdk
        device: MYRIAD
        model:   person-reidentification-retail-0031/FP16/person-reidentification-retail-0031.xml
        weights: person-reidentification-retail-0031/FP16/person-reidentification-retail-0031.bin
        adapter: reid

      - framework: dlsdk
        device: HETERO:FPGA,CPU
        model:   person-reidentification-retail-0031/FP32/person-reidentification-retail-0031.xml
        weights: person-reidentification-retail-0031/FP32/person-reidentification-retail-0031.bin
        adapter: reid
        bitstream: 4-0_A10DK_FP16_ELU.aocx

    datasets:
      - name: market1501
        reader: pillow_imread
        data_source: Market-1501-v15.09.15
        annotation: market1501.pickle

        preprocessing:
          - type: resize
            dst_width: 48
            dst_height: 96
            use_pil: True
            interpolation: ANTIALIAS

        metrics:
          - name: rank@1
            type: cmc
            top_k: 1

          - type: reid_map
