/*
// Copyright (C) 2021 Intel Corporation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
*/

#include "models/model_base.h"
#include <iostream>
#include <inference_engine.hpp>
#include <utils/common.hpp>
#include <utils/slog.hpp>

using namespace InferenceEngine;

void ModelBase::prepareBlobs(const IOPattern& modelIOPattern, const InferenceEngine::InputsDataMap& inputInfo, const InferenceEngine::OutputsDataMap& outputInfo) {
    auto inputsNum = inputInfo.size();
    const auto& inputBlobPattern = modelIOPattern.second[0].patterns.find(inputsNum)->second;
    for (auto& blobName : inputsNames) {
        auto blobPatternIt = inputBlobPattern.find(blobName);
        if (blobPatternIt == inputBlobPattern.end()) {
            blobPatternIt = inputBlobPattern.find("common");
        }
        const auto& blobPatternDesc = blobPatternIt->second;
        const auto& blobData = inputInfo.find(blobName)->second;

        blobData->setPrecision(blobPatternDesc.getPrecision());
        blobData->setLayout(blobPatternDesc.getLayout());
        if (blobData->getTensorDesc().getDims().size() == 4) {
            blobData->getPreProcess().setResizeAlgorithm(InferenceEngine::ResizeAlgorithm::RESIZE_BILINEAR);
        }
    }

    auto outputsNum = outputInfo.size();
    const auto& outputBlobPattern = modelIOPattern.second[1].patterns.find(outputsNum)->second;
    for (const auto& blobName : outputsNames) {
        auto blobPatternIt = outputBlobPattern.find(blobName);
        if (blobPatternIt == outputBlobPattern.end()) {
            blobPatternIt = outputBlobPattern.find("common");
        }
        const auto& blobPatternDesc = blobPatternIt->second;
        const auto& blobData = outputInfo.find(blobName)->second;

        blobData->setPrecision(blobPatternDesc.getPrecision());
        blobData->setLayout(blobPatternDesc.getLayout());
    }
}

void ModelBase::prepareIECore(InferenceEngine::Core& core) {
    // --------------------------- Load inference engine ------------------------------------------------
    slog::info << "Loading Inference Engine" << slog::endl;

    slog::info << "Device info: " << slog::endl;
    slog::info << printable(core.GetVersions(cnnConfig.devices)) << slog::endl;

    /** Load extensions for the plugin **/
    if (!cnnConfig.cpuExtensionsPath.empty()) {
        // CPU(MKLDNN) extensions are loaded as a shared library and passed as a pointer to base extension
        IExtensionPtr extension_ptr = std::make_shared<Extension>(cnnConfig.cpuExtensionsPath);
        core.AddExtension(extension_ptr, "CPU");
    }
    if (!cnnConfig.clKernelsConfigPath.empty()) {
        // clDNN Extensions are loaded from an .xml description and OpenCL kernel files
        core.SetConfig({ {PluginConfigParams::KEY_CONFIG_FILE, cnnConfig.clKernelsConfigPath} }, "GPU");
    }
}

ExecutableNetwork ModelBase::loadExecutableNetwork(const CnnConfig& cnnConfig, InferenceEngine::Core& core) {
    this->cnnConfig = cnnConfig;
    slog::info << "Loading model to the device" << slog::endl;
    prepareIECore(core);
    if (!isNetworkCompiled) {
        // --------------------------- Read IR Generated by ModelOptimizer (.xml and .bin files) ------------
        slog::info << "Loading network files" << slog::endl;
        /** Read network model **/
        InferenceEngine::CNNNetwork cnnNetwork = core.ReadNetwork(modelFileName);
        /** Set batch size to 1 **/
        slog::info << "Batch size is forced to 1." << slog::endl;
        setBatchOne(cnnNetwork);

        // -------------------------- Reading all outputs names and customizing I/O blobs (in inherited classes)
        prepareInputsOutputs(cnnNetwork);
        execNetwork = core.LoadNetwork(cnnNetwork, cnnConfig.devices, cnnConfig.execNetworkConfig);
    }
    else {
        slog::info << "Network is compiled" << slog::endl;
        execNetwork = core.ImportNetwork(modelFileName, cnnConfig.devices, cnnConfig.execNetworkConfig);
        checkCompiledNetworkInputsOutputs();
    }

    return execNetwork;
}
