# Device config example

# Contains device specific options which should be set to Inference Engine.
# For setting device specific flags, you are able to use `-dc` or `--device_config` command line option.
# Device config should be represented as YML file with dictionary of one of two types:
#     1. keys are plugin configuration keys and values are their values respectively.
#        In this way configuration will be applied to current running device.
#     2. keys are supported devices and values are plugin configuration for each device.
#        Plugin configuration represented as dictionary where keys are plugin specific configuration keys and values
#        are their values respectively.
# Each supported device has own set of supported configuration parameters which can be found on
# device page in Inference Engine development guide.

# This config example shows how to disable bfloat16 optimizations for CPU.
# Note: on platforms with native bfloat16 support, ENFORCE_BF16 parameter by default set as "YES",
# for disabling this behavior you need to use device_config with following configuration.
CPU:
   ENFORCE_BF16: "NO"
