#pragma once
enum IMG_RESIZE_MODE {
    RESIZE_FILL,
    RESIZE_KEEP_ASPECT,
    RESIZE_KEEP_ASPECT_LETTERBOX
};

enum IMG_CONVERSION_TYPE {
    CONVERT_NONE,      
    CONVERT_TO_RGB,
    CONVERT_TO_BGR,
};
