models:
  - name: alexnet-cf
    launchers:
      - framework: caffe
        model:   public/alexnet/alexnet.prototxt
        weights: public/alexnet/alexnet.caffemodel
        adapter: classification
    datasets:
      - name: imagenet_1000_classes
        preprocessing:
          - type: resize
            size: 256
          - type: crop
            size: 227
          - type: normalization
            mean: 104, 117, 123

  - name: alexnet
    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   public/alexnet/FP32/alexnet.xml
        weights: public/alexnet/FP32/alexnet.bin
        adapter: classification

      - framework: dlsdk
        tags:
          - FP16
        model:   public/alexnet/FP16/alexnet.xml
        weights: public/alexnet/FP16/alexnet.bin
        adapter: classification

      - framework: dlsdk
        tags:
          - FP32-INT8
        model:   public/alexnet/FP32-INT8/alexnet.xml
        weights: public/alexnet/FP32-INT8/alexnet.bin
        adapter: classification

      - framework: dlsdk
        tags:
          - FP16-INT8
        model:   public/alexnet/FP16-INT8/alexnet.xml
        weights: public/alexnet/FP16-INT8/alexnet.bin
        adapter: classification

    datasets:
      - name: imagenet_1000_classes
        preprocessing:
          - type: resize
            size: 256
          - type: crop
            size: 227

        metrics:
          - name: accuracy@top1
            type: accuracy
            top_k: 1
          - name: accuracy@top5
            type: accuracy
            top_k: 5

global_definitions: ../dataset_definitions.yml
