models:
  - name: asl-recognition-0004

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   intel/asl-recognition-0004/FP32/asl-recognition-0004.xml
        weights: intel/asl-recognition-0004/FP32/asl-recognition-0004.bin
        adapter: classification
        inputs:
          - type: INPUT
            name: input
            layout: NCDHW

      - framework: dlsdk
        tags:
          - FP16
        model:   intel/asl-recognition-0004/FP16/asl-recognition-0004.xml
        weights: intel/asl-recognition-0004/FP16/asl-recognition-0004.bin
        adapter: classification
        inputs:
          - type: INPUT
            name: input
            layout: NCDHW

    datasets:
      - name: msasl-100

        preprocessing:
          - type: resize
            size: 256
            aspect_ratio_scale: greater
          - type: crop
            size: 224
          - type: bgr_to_rgb

        metrics:
          - type: accuracy
            name: rank@1
            top_k: 1

global_definitions: ../dataset_definitions.yml
