models:
  - name: bert-large-uncased-whole-word-masking-squad-fp32-0001
    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model: intel/bert-large-uncased-whole-word-masking-squad-fp32-0001/FP32/bert-large-uncased-whole-word-masking-squad-fp32-0001.xml
        weights: intel/bert-large-uncased-whole-word-masking-squad-fp32-0001/FP32/bert-large-uncased-whole-word-masking-squad-fp32-0001.bin
        adapter:
          type: bert_question_answering
          start_token_logits_output: "3171"
          end_token_logits_output: "3172"
        inputs:
          - name: "0"
            type: INPUT
            value: "input_ids"
          - name: "1"
            type: INPUT
            value: 'input_mask'
          - name: '2'
            type: INPUT
            value: 'segment_ids'

      - framework: dlsdk
        tags:
          - FP16
        model: intel/bert-large-uncased-whole-word-masking-squad-fp32-0001/FP16/bert-large-uncased-whole-word-masking-squad-fp32-0001.xml
        weights: intel/bert-large-uncased-whole-word-masking-squad-fp32-0001/FP16/bert-large-uncased-whole-word-masking-squad-fp32-0001.bin
        adapter:
          type: bert_question_answering
          start_token_logits_output: "3171"
          end_token_logits_output: "3172"
        inputs:
          - name: "0"
            type: INPUT
            value: "input_ids"
          - name: "1"
            type: INPUT
            value: 'input_mask'
          - name: '2'
            type: INPUT
            value: 'segment_ids'

    datasets:
      - name: squad_v1_1_msl384_mql64_ds128_lowercase
        reader:
          type: annotation_features_extractor
          features:
            - input_ids
            - input_mask
            - segment_ids
        postprocessing:
          - type: extract_answers_tokens
            max_answer: 30
            n_best_size: 20
        metrics:
          - name: 'F1'
            type: 'f1'
          - name: 'EM'
            type: 'exact_match'

global_definitions: ../dataset_definitions.yml
