models:
  - name: brain-tumor-segmentation-0002

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   public/brain-tumor-segmentation-0002/FP32/brain-tumor-segmentation-0002.xml
        weights: public/brain-tumor-segmentation-0002/FP32/brain-tumor-segmentation-0002.bin
        adapter:
          type: brain_tumor_segmentation

      - framework: dlsdk
        tags:
          - FP16
        model:   public/brain-tumor-segmentation-0002/FP16/brain-tumor-segmentation-0002.xml
        weights: public/brain-tumor-segmentation-0002/FP16/brain-tumor-segmentation-0002.bin
        adapter:
          type: brain_tumor_segmentation

    datasets:
      - name: BraTS_2017
        preprocessing:
          - type: swap_modalities
            modality_order: [1, 2, 3, 0]
          - type: crop_brats
          - type: normalize_brats
            masked: ignore
          - type: resize3d
            size: (128, 128, 128)
        postprocessing:
          - type: segmentation_prediction_resample
          - type: transform_brats_prediction
            order: [0, 1, 2]
            values: [1, 2, 3]

        metrics:
          - type: dice_index
            median: True
            presenter: print_vector

global_definitions: ../dataset_definitions.yml
