models:
  - name: brain-tumor-segmentation-0001

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   public/brain-tumor-segmentation-0001/FP32/brain-tumor-segmentation-0001.xml
        weights: public/brain-tumor-segmentation-0001/FP32/brain-tumor-segmentation-0001.bin
        adapter:
          type: brain_tumor_segmentation
          make_argmax: True

      - framework: dlsdk
        tags:
          - FP16
        model:   public/brain-tumor-segmentation-0001/FP16/brain-tumor-segmentation-0001.xml
        weights: public/brain-tumor-segmentation-0001/FP16/brain-tumor-segmentation-0001.bin
        adapter:
          type: brain_tumor_segmentation
          make_argmax: True

    datasets:
      - name: BraTS

        metrics:
          # ground truth mean            [0.9239, 0.7114, 0.8205, 0.7271]
          # UNCROPPED: ground truth mean [0.9266, 0.7256, 0.8205, 0.7268]
          # ground truth median             [0.9316, 0.7714, 0.8535, 0.8456]
          # UNCROPPED: ground truth median  [0.9339, 0.7918, 0.8603, 0.8576]
          - type: dice_index
            median: True
            presenter: print_vector

global_definitions: ../dataset_definitions.yml
