models:
  - name: caffenet-cf
    launchers:
      - framework: caffe
        model:   public/caffenet/deploy.prototxt
        weights: public/caffenet/bvlc_reference_caffenet.caffemodel
        adapter: classification
    datasets:
      - name: imagenet_1000_classes
        preprocessing:
          - type: resize
            size: 256
          - type: crop
            size: 227
          - type: normalization
            mean: 104, 117, 123

  - name: caffenet
    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   public/caffenet/FP32/caffenet.xml
        weights: public/caffenet/FP32/caffenet.bin
        adapter: classification

      - framework: dlsdk
        tags:
          - FP16
        model:   public/caffenet/FP16/caffenet.xml
        weights: public/caffenet/FP16/caffenet.bin
        adapter: classification

    datasets:
      - name: imagenet_1000_classes
        preprocessing:
          - type: resize
            size: 256
          - type: crop
            size: 227
