evaluations:
  - name: colorization-v2
    module: custom_evaluators.colorization_evaluator.ColorizationEvaluator
    module_config:
      network_info:
        colorization_network:
          model:   public/colorization-v2/FP32/colorization-v2.xml
          weights: public/colorization-v2/FP32/colorization-v2.bin
          color_coeff: public/colorization-v2/colorization-v2.npy

        verification_network:
          model:   public/vgg16/FP32/vgg16.xml
          weights: public/vgg16/FP32/vgg16.bin
          adapter: classification

      launchers:
        - framework: dlsdk
          tags:
            - FP32

      datasets:
        - name: imagenet_1000_classes
          reader: pillow_imread

          preprocessing:
            - type: resize
              size: 256
              aspect_ratio_scale: greater
            - type: crop
              size: 224
            - type: normalization
              std:  255

  - name: colorization-v2
    module: custom_evaluators.colorization_evaluator.ColorizationEvaluator
    module_config:
      network_info:
        colorization_network:
          model:   public/colorization-v2/FP16/colorization-v2.xml
          weights: public/colorization-v2/FP16/colorization-v2.bin
          color_coeff: public/colorization-v2/colorization-v2.npy

        verification_network:
          model:   public/vgg16/FP32/vgg16.xml
          weights: public/vgg16/FP32/vgg16.bin
          adapter: classification

        launchers:
          - framework: dlsdk
            tags:
              - FP16

        datasets:
          - name: imagenet_1000_classes
            reader: pillow_imread

            preprocessing:
              - type: resize
                size: 256
                aspect_ratio_scale: greater
              - type: crop
                size: 224
              - type: normalization
                std:  255

global_definitions: ../dataset_definitions.yml
