models:

  - name: densenet-121-caffe2
    launchers:
      - framework: onnx_runtime
        model: public/densenet-121-caffe2/densenet-121.onnx
        adapter: classification

    datasets:
      - name: imagenet_1000_classes
        preprocessing:
          - type: resize
            size: 256
            aspect_ratio_scale: greater
          - type: crop
            size: 224
          - type: normalization
            mean: 103.94,116.78,123.68
            std: 58.8235294

  - name: densenet-121-caffe2
    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   public/densenet-121-caffe2/FP32/densenet-121-caffe2.xml
        weights: public/densenet-121-caffe2/FP32/densenet-121-caffe2.bin
        adapter: classification

      - framework: dlsdk
        tags:
          - FP16
        model:   public/densenet-121-caffe2/FP16/densenet-121-caffe2.xml
        weights: public/densenet-121-caffe2/FP16/densenet-121-caffe2.bin
        adapter: classification

    datasets:
      - name: imagenet_1000_classes
        preprocessing:
          - type: resize
            size: 256
            aspect_ratio_scale: greater
          - type: crop
            size: 224

global_definitions: ../dataset_definitions.yml
