evaluations:
  - name: driver-action-recognition-adas-0002-decoder
    module: custom_evaluators.sequential_action_recognition_evaluator.SequentialActionRecognitionEvaluator
    module_config:
      network_info:
        encoder:
          predictions: kinetics/driver-action-recognition-encoder-predictions.pickle

        decoder:
          model:   intel/driver-action-recognition-adas-0002/driver-action-recognition-adas-0002-decoder/FP32/driver-action-recognition-adas-0002-decoder.xml
          weights: intel/driver-action-recognition-adas-0002/driver-action-recognition-adas-0002-decoder/FP32/driver-action-recognition-adas-0002-decoder.bin
          num_processing_frames: 16
          adapter: classification

      launchers:
        - framework: dlsdk
          tags:
            - FP32

      datasets:
        - name: driver_action_recognition_dataset

          preprocessing:
            - type: resize
              size: 224
              aspect_ratio_scale: fit_to_window
            - type: crop
              size: 224

          metrics:
            - type: clip_accuracy

  - name: driver-action-recognition-adas-0002-decoder
    module: custom_evaluators.sequential_action_recognition_evaluator.SequentialActionRecognitionEvaluator
    module_config:
      network_info:
        encoder:
          predictions: kinetics/driver-action-recognition-encoder-predictions.pickle

        decoder:
          model:   intel/driver-action-recognition-adas-0002/driver-action-recognition-adas-0002-decoder/FP16/driver-action-recognition-adas-0002-decoder.xml
          weights: intel/driver-action-recognition-adas-0002/driver-action-recognition-adas-0002-decoder/FP16/driver-action-recognition-adas-0002-decoder.bin
          num_processing_frames: 16
          adapter: classification

      launchers:
        - framework: dlsdk
          tags:
            - FP16

      datasets:
        - name: driver_action_recognition_dataset

          metrics:
            - type: clip_accuracy
              presenter: print_vector

global_definitions: ../dataset_definitions.yml
