models:
  - name: efficientnet-b7-pytorch

    launchers:
      - framework: onnx_runtime
        model: public/efficientnet-b7-pytorch/efficientnet-b7-pytorch.onnx
        adapter: classification
        inputs:
          - name: data
            type: INPUT
            shape: 1,3,600,600

    datasets:
      - name: imagenet_1000_classes
        reader: pillow_imread

        preprocessing:
          - type: resize
            size: 632
            aspect_ratio_scale: greater
            use_pillow: True
            interpolation: BICUBIC
            # Crop ratio 0.949
          - type: crop
            use_pillow: True
            size: 600

          - type: normalization
            mean: (123.675,116.28,103.53)
            std: (58.395,57.12,57.375)

  - name: efficientnet-b7-pytorch

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   public/efficientnet-b7-pytorch/FP32/efficientnet-b7-pytorch.xml
        weights: public/efficientnet-b7-pytorch/FP32/efficientnet-b7-pytorch.bin
        adapter: classification


      - framework: dlsdk
        tags:
          - FP16
        model:   public/efficientnet-b7-pytorch/FP16/efficientnet-b7-pytorch.xml
        weights: public/efficientnet-b7-pytorch/FP16/efficientnet-b7-pytorch.bin
        adapter: classification

    datasets:
      - name: imagenet_1000_classes
        reader: pillow_imread

        preprocessing:
          - type: rgb_to_bgr

          - type: resize
            size: 632
            aspect_ratio_scale: greater
            use_pillow: True
            interpolation: BICUBIC
            # Crop ratio 0.949
          - type: crop
            use_pillow: True
            size: 600

global_definitions: ../dataset_definitions.yml
