models:
  - name: efficientnet-b0

    launchers:
      - framework: tf
        model: public/efficientnet-b0/efficientnet-b0/model.ckpt.meta
        adapter: classification
        output_names:
          - logits
        inputs:
          - name: IteratorGetNext
            type: INPUT

    datasets:
      - name: imagenet_1000_classes
        preprocessing:
          - type: bgr_to_rgb
          - type: crop
            central_fraction: 0.875
            use_pillow: True
          - type: resize
            size: 224
            use_pillow: True
            interpolation: BICUBIC

  - name: efficientnet-b0

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   public/efficientnet-b0/FP32/efficientnet-b0.xml
        weights: public/efficientnet-b0/FP32/efficientnet-b0.bin
        adapter: classification

      - framework: dlsdk
        tags:
          - FP16
        model:   public/efficientnet-b0/FP16/efficientnet-b0.xml
        weights: public/efficientnet-b0/FP16/efficientnet-b0.bin
        adapter: classification

    datasets:
      - name: imagenet_1000_classes
        preprocessing:
          - type: crop
            central_fraction: 0.875
            use_pillow: True
          - type: resize
            size: 224
            use_pillow: True
            interpolation: BICUBIC

global_definitions: ../dataset_definitions.yml
