models:
  - name: face-detection-adas-0001

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   intel/face-detection-adas-0001//FP32/face-detection-adas-0001.xml
        weights: intel/face-detection-adas-0001//FP32/face-detection-adas-0001.bin
        adapter: ssd

      - framework: dlsdk
        tags:
          - FP16
        model:   intel/face-detection-adas-0001/FP16/face-detection-adas-0001.xml
        weights: intel/face-detection-adas-0001/FP16/face-detection-adas-0001.bin
        adapter: ssd

      - framework: dlsdk
        tags:
          - FP16-INT8
        model:   intel/face-detection-adas-0001/FP16-INT8/face-detection-adas-0001.xml
        weights: intel/face-detection-adas-0001/FP16-INT8/face-detection-adas-0001.bin
        adapter: ssd

    datasets:
      - name: wider

        preprocessing:
          - type: resize
            dst_width: 672
            dst_height: 384

        postprocessing:
          - type: resize_prediction_boxes
          - type: filter
            height_range: 100
            apply_to: annotation

        metrics:
          - type: map
            ignore_difficult: True
            include_boundaries: False
            allow_multiple_matches_per_ignored: True
            use_filtered_tp: True

global_definitions: ../dataset_definitions.yml
