models:
  - name: face-detection-0106

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   intel/face-detection-0106/FP32/face-detection-0106.xml
        weights: intel/face-detection-0106/FP32/face-detection-0106.bin
        adapter:
          type: class_agnostic_detection
          scale: 0.0015625

      - framework: dlsdk
        tags:
          - FP16
        model:   intel/face-detection-0106/FP16/face-detection-0106.xml
        weights: intel/face-detection-0106/FP16/face-detection-0106.bin
        adapter:
          type: class_agnostic_detection
          scale: 0.0015625

      - framework: dlsdk
        tags:
          - FP16-INT8
        model:   intel/face-detection-0106/FP16-INT8/face-detection-0106.xml
        weights: intel/face-detection-0106/FP16-INT8/face-detection-0106.bin
        adapter:
          type: class_agnostic_detection
          scale: 0.0015625

    datasets:
      - name: wider

        preprocessing:
          - type: resize
            size: 640

        postprocessing:
          - type: resize_prediction_boxes
          - type: cast_to_int
          - type: clip_boxes
            size: 1024
            apply_to: annotation
          - type: filter
            apply_to: annotation
            height_range: 64, 1024
            is_empty: True

        metrics:
          - type: map
            ignore_difficult: True
            include_boundaries: False
            allow_multiple_matches_per_ignored: True
            distinct_conf: False

global_definitions: ../dataset_definitions.yml
