models:
  - name: face-recognition-resnet50-arcface-mx

    launchers:
      - framework: mxnet
        model: public/face-recognition-resnet50-arcface/model-r50-am-lfw/model-0000.params
        adapter: reid
        inputs:
          - name: data
            type: INPUT
            shape: 3, 112, 112

    datasets:
      - name: lfw

        preprocessing:
          - type: bgr_to_rgb
          - type: point_alignment
            size: 400
          - type: resize
            size: 112

        metrics:
          - type: pairwise_accuracy_subsets

  - name: face-recognition-resnet50-arcface

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   public/face-recognition-resnet50-arcface/FP32/face-recognition-resnet50-arcface.xml
        weights: public/face-recognition-resnet50-arcface//FP32/face-recognition-resnet50-arcface.bin
        adapter: reid

      - framework: dlsdk
        tags:
          - FP16
        model:   public/face-recognition-resnet50-arcface/FP16/face-recognition-resnet50-arcface.xml
        weights: public/face-recognition-resnet50-arcface//FP16/face-recognition-resnet50-arcface.bin
        adapter: reid

    datasets:
      - name: lfw

        preprocessing:
          - type: point_alignment
            size: 400
          - type: resize
            size: 112

global_definitions: ../dataset_definitions.yml
