models:
  - name: faceboxes-pytorch

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   public/faceboxes-pytorch/FP32/faceboxes-pytorch.xml
        weights: public/faceboxes-pytorch/FP32/faceboxes-pytorch.bin
        adapter:
          type: faceboxes
          boxes_out: "342"
          scores_out: "353"

      - framework: dlsdk
        tags:
          - FP16
        model:   public/faceboxes-pytorch/FP16/faceboxes-pytorch.xml
        weights: public/faceboxes-pytorch/FP16/faceboxes-pytorch.bin
        adapter:
          type: faceboxes
          boxes_out: "342"
          scores_out: "353"

    datasets:
      - name: wider

        preprocessing:
          - type: resize
            dst_width: 1024
            dst_height: 1024

        postprocessing:
          - type: resize_prediction_boxes
          - type: filter
            apply_to: annotation
            height_range: 100
            is_empty: True

        metrics:
          - type: map
            ignore_difficult: True
            include_boundaries: False

global_definitions: ../dataset_definitions.yml
