models:
  - name: face-detection-retail-0004

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   Retail/object_detection/face/sqnet1.0modif-ssd/0004/dldt/FP32/face-detection-retail-0004.xml
        weights: Retail/object_detection/face/sqnet1.0modif-ssd/0004/dldt/FP32/face-detection-retail-0004.bin
        adapter: ssd

      - framework: dlsdk
        tags:
          - FP16
        model:   Retail/object_detection/face/sqnet1.0modif-ssd/0004/dldt/FP16/face-detection-retail-0004.xml
        weights: Retail/object_detection/face/sqnet1.0modif-ssd/0004/dldt/FP16/face-detection-retail-0004.bin
        adapter: ssd

      - framework: dlsdk
        tags:
          - INT8
        device: CPU
        model:   Retail/object_detection/face/sqnet1.0modif-ssd/0004/dldt/INT8/face-detection-retail-0004.xml
        weights: Retail/object_detection/face/sqnet1.0modif-ssd/0004/dldt/INT8/face-detection-retail-0004.bin
        adapter: ssd

    datasets:
      - name: wider
        data_source: WIDER_val/images
        annotation_conversion:
          converter: wider
          annotation_file: wider_face_split/wider_face_val_bbx_gt.txt

        preprocessing:
          - type: resize
            size: 300

        postprocessing:
          - type: resize_prediction_boxes
          - type: cast_to_int
          - type: filter
            apply_to: annotation
            height_range: 60
            is_empty: True
          - type: filter
            min_confidence: 0.0
            apply_to: prediction

        metrics:
          - type: map
            ignore_difficult: True
            include_boundaries: False
            allow_multiple_matches_per_ignored: False
            distinct_conf: False
