models:
  - name: face-recognition-resnet100-arcface-mx

    launchers:
      - framework: mxnet
        model: public/face-recognition-resnet100-arcface/model-r100-ii/model-0000.params
        adapter: reid
        inputs:
        - name: data
          type: INPUT
          shape: 3, 112, 112


    datasets:
      - name: lfw
        data_source: LFW/lfw
        annotation_conversion:
          converter: lfw
          pairs_file: LFW/annotation/pairs.txt
          landmarks_file: LFW/annotation/lfw_landmark.txt
        annotation: lfw.pickle

        preprocessing:
          - type: bgr_to_rgb
          - type: point_alignment
            size: 400
          - type: resize
            size: 112

        metrics:
          - type: pairwise_accuracy_subsets

  - name: face-recognition-resnet100-arcface

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   public/face-recognition-resnet100-arcface/FP32/face-recognition-resnet100-arcface.xml
        weights: public/face-recognition-resnet100-arcface/FP32/face-recognition-resnet100-arcface.bin
        adapter: reid

    datasets:
      - name: lfw
        data_source: LFW/lfw
        annotation_conversion:
          converter: lfw
          pairs_file: LFW/annotation/pairs.txt
          landmarks_file: LFW/annotation/lfw_landmark.txt
        annotation: lfw.pickle

        preprocessing:
          - type: point_alignment
            size: 400
          - type: resize
            size: 112

        metrics:
          - type: pairwise_accuracy_subsets
