models:
  - name: face-detection-retail-0004

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   intel/face-detection-retail-0004/FP32/face-detection-retail-0004.xml
        weights: intel/face-detection-retail-0004/FP32/face-detection-retail-0004.bin
        adapter: ssd

      - framework: dlsdk
        tags:
          - FP16
        model:   intel/face-detection-retail-0004/FP16/face-detection-retail-0004.xml
        weights: intel/face-detection-retail-0004/FP16/face-detection-retail-0004.bin
        adapter: ssd

      - framework: dlsdk
        tags:
          - FP16-INT8
        model:   intel/face-detection-retail-0004/FP16-INT8/face-detection-retail-0004.xml
        weights: intel/face-detection-retail-0004/FP16-INT8/face-detection-retail-0004.bin
        adapter: ssd

    datasets:
      - name: wider

        preprocessing:
          - type: resize
            size: 300

        postprocessing:
          - type: resize_prediction_boxes
          - type: cast_to_int
          - type: filter
            apply_to: annotation
            height_range: 60
            is_empty: True
          - type: filter
            min_confidence: 0.0
            apply_to: prediction

        metrics:
          - type: map
            ignore_difficult: True
            include_boundaries: False
            allow_multiple_matches_per_ignored: False
            distinct_conf: False

global_definitions: ../dataset_definitions.yml
