models:
  - name: face-reidentification-retail-0095

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   intel/face-reidentification-retail-0095/FP32/face-reidentification-retail-0095.xml
        weights: intel/face-reidentification-retail-0095/FP32/face-reidentification-retail-0095.bin
        adapter: reid

      - framework: dlsdk
        tags:
          - FP16
        model:   intel/face-reidentification-retail-0095/FP16/face-reidentification-retail-0095.xml
        weights: intel/face-reidentification-retail-0095/FP16/face-reidentification-retail-0095.bin
        adapter: reid

      - framework: dlsdk
        tags:
          - FP16-INT8
        model:   intel/face-reidentification-retail-0095/FP16-INT8/face-reidentification-retail-0095.xml
        weights: intel/face-reidentification-retail-0095/FP16-INT8/face-reidentification-retail-0095.bin
        adapter: reid

    datasets:
      - name: lfw

        preprocessing:
          - type: point_alignment
            size: 400
          - type: resize
            size: 128

global_definitions: ../dataset_definitions.yml
