models:
  - name: face-recognition-resnet34-arcface

    launchers:
      - framework: mxnet
        model: face_recognition/insightface/mxnet/resnet34/model-r34-amf/model-0000.params
        adapter: reid
        inputs:
        - name: data
          type: INPUT
          shape: 3, 112, 112

      - framework: dlsdk
        tags:
          - FP32
        model:   face_recognition/insightface/mxnet/resnet34/FP32/face-recognition-resnet34-arcface.xml
        weights: face_recognition/insightface/mxnet/resnet34/FP32/face-recognition-resnet34-arcface.bin
        adapter: reid

    datasets:
      - name: lfw
        data_source: LFW/lfw
        annotation_conversion:
          converter: face_reid_pairwise
          pairs_file: LFW/annotation/pairs.txt
          landmarks_file: LFW/annotation/lfw_landmark.txt
        annotation: lfw.pickle

        preprocessing:
          - type: point_alignment
            size: 400
          - type: resize
            size: 112

        metrics:
          - type: pairwise_accuracy_subsets
