models:
  - name: facial-landmarks-35-adas-0002

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   intel/facial-landmarks-35-adas-0002/FP32/facial-landmarks-35-adas-0002.xml
        weights: intel/facial-landmarks-35-adas-0002/FP32/facial-landmarks-35-adas-0002.bin
        adapter: landmarks_regression
        cpu_extensions: AUTO

      - framework: dlsdk
        tags:
          - FP16
        model:   intel/facial-landmarks-35-adas-0002/FP16/facial-landmarks-35-adas-0002.xml
        weights: intel/facial-landmarks-35-adas-0002/FP16/facial-landmarks-35-adas-0002.bin
        adapter: landmarks_regression
        cpu_extensions: AUTO

    datasets:
      - name: facial_landmarks_35

        metrics:
          - type: normed_error
            calculate_std: True
            percentile: 90
            presenter: print_vector
