models:
  - name:  faster_rcnn_resnet50_coco
    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   public/faster_rcnn_resnet50_coco/FP32/faster_rcnn_resnet50_coco.xml
        weights: public/faster_rcnn_resnet50_coco/FP32/faster_rcnn_resnet50_coco.bin
        adapter: ssd
        inputs:
          - name: image_info
            type: CONST_INPUT
            value: [[1, 600, 600]]

      - framework: dlsdk
        tags:
          - FP16
        model:   public/faster_rcnn_resnet50_coco/FP16/faster_rcnn_resnet50_coco.xml
        weights: public/faster_rcnn_resnet50_coco/FP16/faster_rcnn_resnet50_coco.bin
        adapter: ssd
        inputs:
          - name: image_info
            type: CONST_INPUT
            value: [[1, 600, 600]]

    datasets:
      - name: ms_coco_detection_91_classes
        preprocessing:
          - type: resize
            size: 600
        postprocessing:
          - type: resize_prediction_boxes
        metrics:
          - type: coco_precision
