models:
  - name:  faster_rcnn_resnet101_coco
    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   public/faster_rcnn_resnet101_coco/FP32/faster_rcnn_resnet101_coco.xml
        weights: public/faster_rcnn_resnet101_coco/FP32/faster_rcnn_resnet101_coco.bin
        adapter: ssd
        inputs:
          - name: image_info
            type: IMAGE_INFO

      - framework: dlsdk
        tags:
          - FP16
        model:   public/faster_rcnn_resnet101_coco/FP16/faster_rcnn_resnet101_coco.xml
        weights: public/faster_rcnn_resnet101_coco/FP16/faster_rcnn_resnet101_coco.bin
        adapter: ssd
        inputs:
          - name: image_info
            type: IMAGE_INFO

    datasets:
      - name: ms_coco_detection_91_classes
        metrics:
          - type: coco_precision
global_definitions: ../dataset_definitions.yml
