models:
  - name: faster_rcnn_inception_v2_coco
    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   public/faster_rcnn_inception_v2_coco/FP32/faster_rcnn_inception_v2_coco.xml
        weights: public/faster_rcnn_inception_v2_coco/FP32/faster_rcnn_inception_v2_coco.bin
        adapter: ssd
        inputs:
          - name: image_info
            type: CONST_INPUT
            value: [[600, 1024, 1]]
      - framework: dlsdk
        tags:
          - FP16
        model:   public/faster_rcnn_inception_v2_coco/FP16/faster_rcnn_inception_v2_coco.xml
        weights: public/faster_rcnn_inception_v2_coco/FP16/faster_rcnn_inception_v2_coco.bin
        adapter: ssd
        inputs:
          - name: image_info
            type: CONST_INPUT
            value: [[600, 1024, 1]]

    datasets:
      - name: ms_coco_detection_91_classes
        metrics:
          - type: coco_precision
            max_detections: 100

global_definitions: ../dataset_definitions.yml
