models:
  - name: googlenet-v2-cf
    launchers:
      - framework: caffe
        model:   public/googlenet-v2/googlenet-v2.prototxt
        weights: public/googlenet-v2/googlenet-v2.caffemodel
        adapter: classification

    datasets:
      - name: imagenet_1000_classes_2015
        preprocessing:
          - type: resize
            size: 256
          - type: crop
            size: 224
          - type: normalization
            mean: 104, 117, 123

  - name: googlenet-v2
    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   public/googlenet-v2/FP32/googlenet-v2.xml
        weights: public/googlenet-v2/FP32/googlenet-v2.bin
        adapter: classification

      - framework: dlsdk
        tags:
          - FP16
        model:   public/googlenet-v2/FP16/googlenet-v2.xml
        weights: public/googlenet-v2/FP16/googlenet-v2.bin
        adapter: classification

    datasets:
      - name: imagenet_1000_classes_2015
        preprocessing:
          - type: resize
            size: 256
          - type: crop
            size: 224

global_definitions: ../dataset_definitions.yml
