models:
  - name: googlenet-v1-cf
    launchers:
      - framework: caffe
        model:   public/googlenet-v1/googlenet-v1.prototxt
        weights: public/googlenet-v1/googlenet-v1.caffemodel
        adapter: classification

    datasets:
      - name: imagenet_1000_classes
        preprocessing:
          - type: resize
            size: 256
          - type: crop
            size: 224
          - type: normalization
            mean: 104, 117, 123

  - name: googlenet-v1
    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   public/googlenet-v1/FP32/googlenet-v1.xml
        weights: public/googlenet-v1/FP32/googlenet-v1.bin
        adapter: classification

      - framework: dlsdk
        tags:
          - FP16
        model:   public/googlenet-v1/FP16/googlenet-v1.xml
        weights: public/googlenet-v1/FP16/googlenet-v1.bin
        adapter: classification

      - framework: dlsdk
        tags:
          - FP32-INT8
        model:   public/googlenet-v1/FP32-INT8/googlenet-v1.xml
        weights: public/googlenet-v1/FP32-INT8/googlenet-v1.bin
        adapter: classification

      - framework: dlsdk
        tags:
          - FP16-INT8
        model:   public/googlenet-v1/FP16-INT8/googlenet-v1.xml
        weights: public/googlenet-v1/FP16-INT8/googlenet-v1.bin
        adapter: classification

    datasets:
      - name: imagenet_1000_classes
        preprocessing:
          - type: resize
            size: 256
          - type: crop
            size: 224

global_definitions: ../dataset_definitions.yml
