models:
  - name: handwritten-japanese-recognition-0001

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   intel/handwritten-japanese-recognition-0001/FP32/handwritten-japanese-recognition-0001.xml
        weights: intel/handwritten-japanese-recognition-0001/FP32/handwritten-japanese-recognition-0001.bin
        adapter: ctc_greedy_search_decoder

      - framework: dlsdk
        tags:
          - FP16
        model:   intel/handwritten-japanese-recognition-0001/FP16/handwritten-japanese-recognition-0001.xml
        weights: intel/handwritten-japanese-recognition-0001/FP16/handwritten-japanese-recognition-0001.bin
        adapter: ctc_greedy_search_decoder

      - framework: dlsdk
        tags:
          - FP16-INT8
        model:   intel/handwritten-japanese-recognition-0001/FP16-INT8/handwritten-japanese-recognition-0001.xml
        weights: intel/handwritten-japanese-recognition-0001/FP16-INT8/handwritten-japanese-recognition-0001.bin
        adapter: ctc_greedy_search_decoder

    datasets:
      - name: Kondate_nakayosi
        # In order to be used by model, images must be:
        # 1) Resized to fixed height 96, using AREA interpolation
        # 2) Padded with edge padding, right padding only
        preprocessing:
          - type: bgr_to_gray
          - type: resize
            interpolation: AREA
            aspect_ratio_scale: width
            size: 96
          - type: padding
            use_numpy: True
            numpy_pad_mode: edge
            dst_height: 96
            dst_width: 2000
            pad_type: right_bottom

        metrics:
          - type: label_level_recognition_accuracy

global_definitions: ../dataset_definitions.yml
