models:
  - name: icnet-camvid-onnx-0001

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   intel/icnet-camvid-onnx-0001/FP32/icnet-camvid-onnx-0001.xml
        weights: intel/icnet-camvid-onnx-0001/FP32/icnet-camvid-onnx-0001.bin
        adapter: segmentation

      - framework: dlsdk
        tags:
          - FP16
        model:   intel/icnet-camvid-onnx-0001/FP16/icnet-camvid-onnx-0001.xml
        weights: intel/icnet-camvid-onnx-0001/FP16/icnet-camvid-onnx-0001.bin
        adapter: segmentation

    datasets:
      - name: CamVid
        reader: pillow_imread

        preprocessing:
          - type: resize
            dst_height: 768
            dst_width: 960
            use_pillow: True
            interpolation: BILINEAR
          - type: bgr_to_rgb

        postprocessing:
          - type: resize_segmentation_mask
            apply_to: annotation
            dst_height: 768
            dst_width: 960

        metrics:
          - type: mean_iou
            use_argmax: True
            presenter: print_vector

global_definitions: ../dataset_definitions.yml
