models:
  - name: icnet-camvid-ava-sparse-30-0001

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model: intel/icnet-camvid-ava-sparse-30-0001/FP32/icnet-camvid-ava-sparse-30-0001.xml
        weights: intel/icnet-camvid-ava-sparse-30-0001/FP32/icnet-camvid-ava-sparse-30-0001.bin
        adapter: segmentation
      - framework: dlsdk
        tags:
          - FP16
        model: intel/icnet-camvid-ava-sparse-30-0001/FP16/icnet-camvid-ava-sparse-30-0001.xml
        weights: intel/icnet-camvid-ava-sparse-30-0001/FP16/icnet-camvid-ava-sparse-30-0001.bin
        adapter: segmentation
      - framework: dlsdk
        tags:
          - FP16-INT8
        model: intel/icnet-camvid-ava-sparse-30-0001/FP16-INT8/icnet-camvid-ava-sparse-30-0001.xml
        weights: intel/icnet-camvid-ava-sparse-30-0001/FP16-INT8/icnet-camvid-ava-sparse-30-0001.bin
        adapter: segmentation
    datasets:
      - name: CamVid

        preprocessing:
          - type: resize
            dst_width: 960
            dst_height: 720
            interpolation: LINEAR

        postprocessing:
          - type: resize_segmentation_mask
            apply_to: annotation
            dst_width: 960
            dst_height: 720

        metrics:
          - type: mean_iou
            use_argmax: false

global_definitions: ../dataset_definitions.yml
