models:
  - name: image-retrieval-0001

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   intel/image-retrieval-0001/FP32/image-retrieval-0001.xml
        weights: intel/image-retrieval-0001/FP32/image-retrieval-0001.bin
        adapter: reid

      - framework: dlsdk
        tags:
          - FP16
        model:   intel/image-retrieval-0001/FP16/image-retrieval-0001.xml
        weights: intel/image-retrieval-0001/FP16/image-retrieval-0001.bin
        adapter: reid

      - framework: dlsdk
        tags:
          - FP16-INT8
        model:   intel/image-retrieval-0001/FP16-INT8/image-retrieval-0001.xml
        weights: intel/image-retrieval-0001/FP16-INT8/image-retrieval-0001.bin
        adapter: reid

    datasets:
      - name: image_retrieval

        metrics:
          - name: rank@1
            type: cmc
            top_k: 1

          - type: reid_map

global_definitions: ../dataset_definitions.yml
