models:
  - name: inception-resnet-v2-cf
    launchers:
      - framework: caffe
        model:   public/inception-resnet-v2/inception-resnet-v2.prototxt
        weights: public/inception-resnet-v2/inception-resnet-v2.caffemodel
        adapter: classification
    datasets:
      - name: imagenet_1000_classes
        preprocessing:
          - type: resize
            size: 320
          - type: crop
            size: 299
          - type: normalization
            mean: 104, 117, 123

  - name: inception-resnet-v2
    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   public/inception-resnet-v2/FP32/inception-resnet-v2.xml
        weights: public/inception-resnet-v2/FP32/inception-resnet-v2.bin
        adapter: classification

      - framework: dlsdk
        tags:
          - FP16
        model:   public/inception-resnet-v2/FP16/inception-resnet-v2.xml
        weights: public/inception-resnet-v2/FP16/inception-resnet-v2.bin
        adapter: classification
    datasets:
      - name: imagenet_1000_classes
        preprocessing:
          - type: resize
            size: 320
          - type: crop
            size: 299
