models:
  - name: instance-segmentation-security-0083

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   intel/instance-segmentation-security-0083/FP32/instance-segmentation-security-0083.xml
        weights: intel/instance-segmentation-security-0083/FP32/instance-segmentation-security-0083.bin
        adapter:
          type: mask_rcnn
          classes_out: classes
          scores_out: scores
          boxes_out: boxes
          raw_masks_out: raw_masks
        inputs:
          - name: im_info
            type: IMAGE_INFO

      - framework: dlsdk
        tags:
          - FP16
        model:   intel/instance-segmentation-security-0083/FP16/instance-segmentation-security-0083.xml
        weights: intel/instance-segmentation-security-0083/FP16/instance-segmentation-security-0083.bin
        adapter:
          type: mask_rcnn
          classes_out: classes
          scores_out: scores
          boxes_out: boxes
          raw_masks_out: raw_masks
        inputs:
          - name: im_info
            type: IMAGE_INFO

      - framework: dlsdk
        tags:
          - FP16-INT8
        model:   intel/instance-segmentation-security-0083/FP16-INT8/instance-segmentation-security-0083.xml
        weights: intel/instance-segmentation-security-0083/FP16-INT8/instance-segmentation-security-0083.bin
        adapter:
          type: mask_rcnn
          classes_out: classes
          scores_out: scores
          boxes_out: boxes
          raw_masks_out: raw_masks
        inputs:
          - name: im_info
            type: IMAGE_INFO

    datasets:
      - name: ms_coco_mask_rcnn_short_80_classes

        preprocessing:
          - type: resize
            dst_width: 640
            dst_height: 480
            aspect_ratio_scale: fit_to_window
          - type: padding
            dst_width: 640
            dst_height: 480
            pad_type: right_bottom
            use_numpy: True

        metrics:
          - name: AP@masks
            type: coco_orig_segm_precision

          - name: AP@boxes
            type: coco_orig_precision

global_definitions: ../dataset_definitions.yml
