models:
  - name: landmarks-regression-retail-0009

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   intel/landmarks-regression-retail-0009/FP32/landmarks-regression-retail-0009.xml
        weights: intel/landmarks-regression-retail-0009/FP32/landmarks-regression-retail-0009.bin
        adapter: landmarks_regression

      - framework: dlsdk
        tags:
          - FP16
        model:   intel/landmarks-regression-retail-0009/FP16/landmarks-regression-retail-0009.xml
        weights: intel/landmarks-regression-retail-0009/FP16/landmarks-regression-retail-0009.bin
        adapter: landmarks_regression

    datasets:
      - name: vgg2face
        data_source: VGGFaces2/test
        annotation_conversion:
          converter: vgg_face
          landmarks_csv_file: VGGFaces2/bb_landmark/loose_landmark_test.csv
          bbox_csv_file: VGGFaces2/bb_landmark/loose_bb_test.csv

        preprocessing:
          - type: crop_rect
          - type: resize
            size: 48

        postprocessing:
          - type: normalize_landmarks_points
            use_annotation_rect: True

        metrics:
          - type: per_point_normed_error
            presenter: print_vector
          - type: normed_error
