models:
  - name: landmarks-regression-retail-0009

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   intel/landmarks-regression-retail-0009/FP32/landmarks-regression-retail-0009.xml
        weights: intel/landmarks-regression-retail-0009/FP32/landmarks-regression-retail-0009.bin
        adapter: landmarks_regression

      - framework: dlsdk
        tags:
          - FP16
        model:   intel/landmarks-regression-retail-0009/FP16/landmarks-regression-retail-0009.xml
        weights: intel/landmarks-regression-retail-0009/FP16/landmarks-regression-retail-0009.bin
        adapter: landmarks_regression

      - framework: dlsdk
        tags:
          - FP16-INT8
        model:   intel/landmarks-regression-retail-0009/FP16-INT8/landmarks-regression-retail-0009.xml
        weights: intel/landmarks-regression-retail-0009/FP16-INT8/landmarks-regression-retail-0009.bin
        adapter: landmarks_regression

    datasets:
      - name: vgg2face

        preprocessing:
          - type: crop_rect
          - type: resize
            size: 48

        postprocessing:
          - type: normalize_landmarks_points
            use_annotation_rect: True

        metrics:
          - type: per_point_normed_error
            presenter: print_vector
          - type: normed_error

global_definitions: ../dataset_definitions.yml
