models:
  - name: license-plate-recognition-barrier-0001

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   intel/license-plate-recognition-barrier-0001/FP32/license-plate-recognition-barrier-0001.xml
        weights: intel/license-plate-recognition-barrier-0001/FP32/license-plate-recognition-barrier-0001.bin
        adapter: lpr
        cpu_extensions: AUTO
        inputs:
          - name: seq_ind
            type: CONST_INPUT
            value: [[0], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1]]

      - framework: dlsdk
        tags:
          - FP16
        model:   intel/license-plate-recognition-barrier-0001/FP16/license-plate-recognition-barrier-0001.xml
        weights: intel/license-plate-recognition-barrier-0001/FP16/license-plate-recognition-barrier-0001.bin
        adapter: lpr
        cpu_extensions: AUTO
        inputs:
          - name: seq_ind
            type: CONST_INPUT
            value: [[0], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1]]

      - framework: dlsdk
        tags:
          - INT8
        model:   intel/license-plate-recognition-barrier-0001/INT8/license-plate-recognition-barrier-0001.xml
        weights: intel/license-plate-recognition-barrier-0001/INT8/license-plate-recognition-barrier-0001.bin
        adapter: lpr
        cpu_extensions: AUTO
        inputs:
          - name: seq_ind
            type: CONST_INPUT
            value: [[0], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1]]

    datasets:
      - name: synthetic_chinese_license_plates

        preprocessing:
          - type: resize
            dst_width: 94
            dst_height: 24

        metrics:
          - type: character_recognition_accuracy
