models:
  - name: mask_rcnn_R_50_FPN_1x

    launchers:
      - framework: dlsdk
        model:   mask_rcnn_R_50_FPN_1x.xml
        weights: mask_rcnn_R_50_FPN_1x.bin
        outputs:
          - DetectionOutput,0
          - DetectionOutput,1
          - DetectionOutput,2
        adapter:
          type: mask_rcnn
          classes_out: DetectionOutput.1
          scores_out: DetectionOutput.2
          boxes_out: DetectionOutput.0
          raw_masks_out: "68497859"
        cpu_extensions: AUTO
        inputs:
          - name: im_info
            type: IMAGE_INFO

    datasets:
      - name: ms_coco_mask_rcnn_80_classes_bkgr
        data_source: /home/automation/datasets/MSCOCO/data/val2017
        annotation_conversion:
          converter: mscoco_mask_rcnn
          annotation_file: /home/automation/instances_val2017_300.json
          has_background: True
          sort_annotations: True
        annotation: mscoco_mask_rcnn.pickle
        dataset_meta: mscoco_mask_rcnn.json

        preprocessing:
          - type: resize
            dst_width: 480
            dst_height: 352
            aspect_ratio_scale: fit_to_window
          - type: padding
            dst_width: 480
            dst_height: 352
            pad_type: right_bottom
            use_numpy: True

        metrics:
          - name: AP@masks
            type: coco_orig_segm_precision

          - name: AP@boxes
            type: coco_orig_precision
global_definitions: ../dataset_definitions.yml
