models:
  - name: midasnet
    launchers:
      - framework: dlsdk
        tags:
          - FP16
        model: public/midasnet/FP16/midasnet.xml
        weights: public/midasnet/FP16/midasnet.bin
        adapter: mono_depth
      - framework: dlsdk
        tags:
          - FP32
        model: public/midasnet/FP32/midasnet.xml
        weights: public/midasnet/FP32/midasnet.bin
        adapter: mono_depth
    datasets:
      - name: ReDWeb_V1
        preprocessing:
          - type: resize
            size: 384
        postprocessing:
          - type: resize_prediction_depth_map
          - type: align_prediction_depth_map
        metrics:
          - type: rmse

global_definitions: ../dataset_definitions.yml
