models:
  - name: mobilenet-v1-1.0-224-cf
    launchers:
      - framework: caffe
        model:   public/mobilenet-v1-1.0-224/mobilenet-v1-1.0-224.prototxt
        weights: public/mobilenet-v1-1.0-224/mobilenet-v1-1.0-224.caffemodel
        adapter: classification
    datasets:
      - name: imagenet_1000_classes
        preprocessing:
          - type: resize
            size: 256
          - type: crop
            size: 224
          - type: normalization
            mean: 103.94, 116.78, 123.68
            std: 58.8235294

  - name: mobilenet-v1-1.0-224
    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   public/mobilenet-v1-1.0-224/FP32/mobilenet-v1-1.0-224.xml
        weights: public/mobilenet-v1-1.0-224/FP32/mobilenet-v1-1.0-224.bin
        adapter: classification

      - framework: dlsdk
        tags:
          - FP16
        model:   public/mobilenet-v1-1.0-224/FP16/mobilenet-v1-1.0-224.xml
        weights: public/mobilenet-v1-1.0-224/FP16/mobilenet-v1-1.0-224.bin
        adapter: classification

      - framework: dlsdk
        tags:
          - FP32-INT8
        model:   public/mobilenet-v1-1.0-224/FP32-INT8/mobilenet-v1-1.0-224.xml
        weights: public/mobilenet-v1-1.0-224/FP32-INT8/mobilenet-v1-1.0-224.bin
        adapter: classification

      - framework: dlsdk
        tags:
          - FP16-INT8
        model:   public/mobilenet-v1-1.0-224/FP16-INT8/mobilenet-v1-1.0-224.xml
        weights: public/mobilenet-v1-1.0-224/FP16-INT8/mobilenet-v1-1.0-224.bin
        adapter: classification

    datasets:
      - name: imagenet_1000_classes
        preprocessing:
          - type: resize
            size: 256
          - type: crop
            size: 224

global_definitions: ../dataset_definitions.yml
