models:
  - name: ssd-mobilenet-cf
    launchers:
      - framework: caffe
        model:   public/mobilenet-ssd/mobilenet-ssd.prototxt
        weights: public/mobilenet-ssd/mobilenet-ssd.caffemodel
        adapter: ssd
    datasets:
      - name: VOC2012
        preprocessing:
          - type: resize
            size: 300
          - type: normalization
            mean: 127.5
            std:  127.5
        postprocessing:
          - type: resize_prediction_boxes

  - name: ssd-mobilenet
    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   public/mobilenet-ssd/FP32/mobilenet-ssd.xml
        weights: public/mobilenet-ssd/FP32/mobilenet-ssd.bin
        adapter: ssd
        cpu_extensions: AUTO

      - framework: dlsdk
        tags:
          - FP16
        model:   public/mobilenet-ssd/FP16/mobilenet-ssd.xml
        weights: public/mobilenet-ssd/FP16/mobilenet-ssd.bin
        adapter: ssd
        cpu_extensions: AUTO

    datasets:
      - name: VOC2012
        preprocessing:
          - type: resize
            size: 300
        postprocessing:
          - type: resize_prediction_boxes
