models:
  - name: mtcnn-p

    launchers:
      - framework: caffe
        model:   public/mtcnn/mtcnn-p/mtcnn-p.prototxt
        weights: public/mtcnn/mtcnn-p/mtcnn-p.caffemodel
        inputs:
          - name: data
            type: INPUT
            layout: NCWH
        adapter:
          type: mtcnn_p
          probability_out: prob1
          region_out: conv4-2
        allow_reshape_input: True

    datasets:
      - name: wider

        preprocessing:
          - type: bgr_to_rgb
          - type: pyramid
            min_size: 20
            factor: 0.709
          - type: normalization
            mean: 127.5
            std: 128

        postprocessing:
          - type: cast_to_int
          - type: filter
            apply_to: annotation
            height_range: 60
            is_empty: True
          - type: filter
            min_confidence: 0.99
            apply_to: prediction
            remove_filtered: True

        metrics:
          - type: map
            ignore_difficult: True
            include_boundaries: False
            allow_multiple_matches_per_ignored: False
            distinct_conf: False

  - name: mtcnn-p

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   public/mtcnn/mtcnn-p/FP32/mtcnn-p.xml
        weights: public/mtcnn/mtcnn-p/FP32/mtcnn-p.bin
        inputs:
          - name: data
            type: INPUT
            layout: NCWH
        adapter:
          type: mtcnn_p
          probability_out: prob1
          region_out: conv4-2
        allow_reshape_input: True

      - framework: dlsdk
        tags:
          - FP16
        model:   public/mtcnn/mtcnn-p/FP16/mtcnn-p.xml
        weights: public/mtcnn/mtcnn-p/FP16/mtcnn-p.bin
        inputs:
          - name: data
            type: INPUT
            layout: NCWH
        adapter:
          type: mtcnn_p
          probability_out: prob1
          region_out: conv4-2
        allow_reshape_input: True

    datasets:
      - name: wider

        preprocessing:
          - type: bgr_to_rgb
          - type: pyramid
            min_size: 20
            factor: 0.709

        postprocessing:
          - type: cast_to_int
          - type: filter
            apply_to: annotation
            height_range: 60
            is_empty: True
          - type: filter
            min_confidence: 0.99
            apply_to: prediction
            remove_filtered: True

        metrics:
          - type: map
            ignore_difficult: True
            include_boundaries: False
            allow_multiple_matches_per_ignored: False
            distinct_conf: False
global_definitions: ../dataset_definitions.yml
