evaluations:
  - name: mtcnn-o
    module: custom_evaluators.mtcnn_evaluator.MTCNNEvaluator
    module_config:
      network_info:
        pnet:
          model:   public/mtcnn-p/mtcnn-p.prototxt
          weights: public/mtcnn-p/mtcnn-p.prototxt
          outputs:
            probability_out: prob1
            region_out: conv4-2
          inputs:
            - name: data
              type: INPUT
              layout: NCWH
          preprocessing:
            - type: bgr_to_rgb
            - type: pyramid
              min_size: 10
              factor: 0.79
          adapter:
            type: mtcnn_p
            probability_out: prob1
            region_out: conv4-2
            regions_format: hw

          rnet:
            model:   public/mtcnn-r/mtcnn-r.prototxt
            weights: public/mtcnn-r/mtcnn-r.prototxt
            outputs:
              probability_out: prob1
              region_out: conv5-2
            inputs:
              - name: data
                type: INPUT
                layout: NCWH
            preprocessing:
              - type: bgr_to_rgb
          onet:
            model:   public/mtcnn-o/mtcnn-o.prototxt
            weights: public/mtcnn-o/mtcnn-o.prototxt
            outputs:
              probability_out: prob1
              region_out: conv6-2
            inputs:
              - name: data
                type: INPUT
                layout: NCWH
            preprocessing:
              - type: bgr_to_rgb

      launchers:
        - framework: caffe

      datasets:
        - name: wider

          preprocessing:
            - type: normalization
              mean: 127.5
              std: 128

          postprocessing:
            - type: filter
              apply_to: prediction
              is_empty: True
            - type: filter
              height_range: 60
              apply_to: annotation

          metrics:
            - type: recall
              ignore_difficult: True
              include_boundaries: True
              allow_multiple_matches_per_ignored: True
              distinct_conf: False

            - type: map
              ignore_difficult: True
              include_boundaries: True
              allow_multiple_matches_per_ignored: True
              distinct_conf: False

  - name: mtcnn-o
    module: custom_evaluators.mtcnn_evaluator.MTCNNEvaluator
    module_config:
      network_info:
        pnet:
          model:   public/mtcnn-p/FP32/mtcnn-p.xml
          weights: public/mtcnn-p/FP32/mtcnn-p.bin
          outputs:
            probability_out: prob1
            region_out: conv4-2
          inputs:
            - name: data
              type: INPUT
              layout: NCWH
          preprocessing:
            - type: bgr_to_rgb
            - type: pyramid
              min_size: 10
              factor: 0.79

        rnet:
          model:   public/mtcnn-r/FP32/mtcnn-r.xml
          weights: public/mtcnn-r/FP32/mtcnn-r.bin
          outputs:
            probability_out: prob1
            region_out: conv5-2
          inputs:
            - name: data
              type: INPUT
              layout: NCWH
          preprocessing:
            - type: bgr_to_rgb

        onet:
          model:   public/mtcnn-o/FP32/mtcnn-o.xml
          weights: public/mtcnn-o/FP32/mtcnn-o.bin
          outputs:
            probability_out: prob1
            region_out: conv6-2
          inputs:
            - name: data
              type: INPUT
              layout: NCWH
          preprocessing:
            - type: bgr_to_rgb

      launchers:
        - framework: dlsdk
          tags:
            - FP32

      datasets:
        - name: wider

          postprocessing:
            - type: filter
              apply_to: prediction
              is_empty: True
            - type: filter
              height_range: 60
              apply_to: annotation

          metrics:
            - type: recall
              ignore_difficult: True
              include_boundaries: True
              allow_multiple_matches_per_ignored: True
              distinct_conf: False

            - type: map
              ignore_difficult: True
              include_boundaries: True
              allow_multiple_matches_per_ignored: True
              distinct_conf: False

  - name: mtcnn-o
    module: custom_evaluators.mtcnn_evaluator.MTCNNEvaluator
    module_config:
      network_info:
        pnet:
          model:   public/mtcnn-p/FP16/mtcnn-p.xml
          weights: public/mtcnn-p/FP16/mtcnn-p.bin
          outputs:
            probability_out: prob1
            region_out: conv4-2
          inputs:
            - name: data
              type: INPUT
              layout: NCWH
          preprocessing:
            - type: bgr_to_rgb
            - type: pyramid
              min_size: 10
              factor: 0.79

        rnet:
          model:   public/mtcnn-r/FP16/mtcnn-r.xml
          weights: public/mtcnn-r/FP16/mtcnn-r.bin
          outputs:
            probability_out: prob1
            region_out: conv5-2
          inputs:
            - name: data
              type: INPUT
              layout: NCWH
          preprocessing:
            - type: bgr_to_rgb

        onet:
          model:   public/mtcnn-o/FP16/mtcnn-o.xml
          weights: public/mtcnn-o/FP16/mtcnn-o.bin
          outputs:
            probability_out: prob1
            region_out: conv6-2
          inputs:
            - name: data
              type: INPUT
              layout: NCWH
          preprocessing:
            - type: bgr_to_rgb

      launchers:
        - framework: dlsdk
          tags:
            - FP16

      datasets:
        - name: wider

          postprocessing:
            - type: filter
              apply_to: prediction
              is_empty: True
            - type: filter
              height_range: 60
              apply_to: annotation

          metrics:
            - type: recall
              ignore_difficult: True
              include_boundaries: True
              allow_multiple_matches_per_ignored: True
              distinct_conf: False

            - type: map
              ignore_difficult: True
              include_boundaries: True
              allow_multiple_matches_per_ignored: True
              distinct_conf: False

global_definitions: ../dataset_definitions.yml
