evaluations:
  - name: mtcnn-r
    module: custom_evaluators.mtcnn_evaluator.MTCNNEvaluator
    module_config:
      network_info:
        pnet:
          predictions: pnet_predictions.pickle

        rnet:
          model:   public/mtcnn/mtcnn-r/mtcnn-r.prototxt
          weights: public/mtcnn/mtcnn-r/mtcnn-r.caffemodel
          outputs:
            probability_out: prob1
            region_out: conv5-2
          inputs:
            - name: data
              type: INPUT
              layout: NCWH
          preprocessing:
            - type: bgr_to_rgb

      launchers:
        - framework: caffe

      datasets:
        - name: wider

          preprocessing:
            - type: normalization
              mean: 127.5
              std: 128

          postprocessing:
            - type: filter
              apply_to: prediction
              is_empty: True
            - type: filter
              height_range: 60
              apply_to: annotation

          metrics:
            - type: recall
              ignore_difficult: True
              include_boundaries: True
              allow_multiple_matches_per_ignored: True
              distinct_conf: False

            - type: map
              ignore_difficult: True
              include_boundaries: True
              allow_multiple_matches_per_ignored: True
              distinct_conf: False

  - name: mtcnn-r
    module: custom_evaluators.mtcnn_evaluator.MTCNNEvaluator
    module_config:
      network_info:
        pnet:
          predictions: pnet_predictions.pickle

        rnet:
          model:   public/mtcnn/mtcnn-r/FP32/mtcnn-r.xml
          weights: public/mtcnn/mtcnn-r/FP32/mtcnn-r.xml
          outputs:
            probability_out: prob1
            region_out: conv5-2
          inputs:
            - name: data
              type: INPUT
              layout: NCWH
          preprocessing:
            - type: bgr_to_rgb

      launchers:
        - framework: dlsdk
          tags:
            - FP32

      datasets:
        - name: wider

          postprocessing:
            - type: filter
              apply_to: prediction
              is_empty: True
            - type: filter
              height_range: 60
              apply_to: annotation

          metrics:
            - type: recall
              ignore_difficult: True
              include_boundaries: True
              allow_multiple_matches_per_ignored: True
              distinct_conf: False

            - type: map
              ignore_difficult: True
              include_boundaries: True
              allow_multiple_matches_per_ignored: True
              distinct_conf: False

  - name: mtcnn-r
    module: custom_evaluators.mtcnn_evaluator.MTCNNEvaluator
    module_config:
      network_info:
        pnet:
          predictions: pnet_predictions.pickle

        rnet:
          model:   public/mtcnn/mtcnn-r/FP16/mtcnn-r.xml
          weights: public/mtcnn/mtcnn-r/FP16/mtcnn-r.xml
          outputs:
            probability_out: prob1
            region_out: conv5-2
          inputs:
            - name: data
              type: INPUT
              layout: NCWH
          preprocessing:
            - type: bgr_to_rgb

      launchers:
        - framework: dlsdk
          tags:
            - FP16

      datasets:
        - name: wider

          postprocessing:
            - type: filter
              apply_to: prediction
              is_empty: True
            - type: filter
              height_range: 60
              apply_to: annotation

          metrics:
            - type: recall
              ignore_difficult: True
              include_boundaries: True
              allow_multiple_matches_per_ignored: True
              distinct_conf: False

            - type: map
              ignore_difficult: True
              include_boundaries: True
              allow_multiple_matches_per_ignored: True
              distinct_conf: False

global_definitions: ../dataset_definitions.yml
