models:
  - name: open-closed-eye-0001
    launchers:
      - framework: onnx_runtime
        model: public/open-closed-eye-0001/open-closed-eye.onnx
        adapter: classification
    datasets:
      - name: mrlEyes_2018_01
        preprocessing:
          - type: resize
            size: 32
          - type: normalization
            mean: 127.0, 127.0, 127.0
            std: 255.0, 255.0, 255.0
        metrics:
          - type: accuracy
  - name: open-closed-eye-0001
    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   public/open-closed-eye-0001/FP32/open-closed-eye-0001.xml
        weights: public/open-closed-eye-0001/FP32/open-closed-eye-0001.bin
        adapter: classification
      - framework: dlsdk
        tags:
          - FP16
        model:   public/open-closed-eye-0001/FP16/open-closed-eye-0001.xml
        weights: public/open-closed-eye-0001/FP16/open-closed-eye-0001.bin
        adapter: classification
    datasets:
      - name: mrlEyes_2018_01
        preprocessing:
          - type: resize
            size: 32
        metrics:
          - type: accuracy
global_definitions: ../dataset_definitions.yml
