models:
  - name: pelee-coco

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   public/pelee-coco/FP32/pelee-coco.xml
        weights: public/pelee-coco/FP32/pelee-coco.bin
        adapter: ssd

      - framework: dlsdk
        tags:
          - FP16
        model:   pelee-coco/FP16/pelee-coco.xml
        weights: pelee-coco/FP16/pelee-coco.bin
        adapter: ssd

    datasets:
      - name: ms_coco_detection_80_class_with_background

        preprocessing:
          - type: resize
            dst_width: 304
            dst_height: 304

        postprocessing:
          - type: resize_prediction_boxes

        metrics:
          - type: coco_precision
            max_detections: 100

global_definitions: ../dataset_definitions.yml
