models:
  - name: person-detection-0102

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   intel/person-detection-0102/FP32/person-detection-0102.xml
        weights: intel/person-detection-0102/FP32/person-detection-0102.bin
        adapter: ssd

      - framework: dlsdk
        tags:
          - FP16
        model:   intel/person-detection-0102/FP16/person-detection-0102.xml
        weights: intel/person-detection-0102/FP16/person-detection-0102.bin
        adapter: ssd

    datasets:
      - name: person_detection

        preprocessing:
          - type: resize
            dst_width: 512
            dst_height: 512

        postprocessing:
          - type: resize_prediction_boxes
          - type: filter
            apply_to: annotation
            height_range: 100
            aspect_ratio: 0.666, 5
            is_empty: True
            min_visibility: partially occluded
          - type: filter
            apply_to: prediction
            height_range: 100
            is_empty: True
            aspect_ratio: 0.666, 5

        metrics:
          - type: map
            ignore_difficult: True
            include_boundaries: True
            allow_multiple_matches_per_ignored: False
            distinct_conf: False

global_definitions: ../dataset_definitions.yml
