models:
  - name: person-detection-action-recognition-0005

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   intel/person-detection-action-recognition-0005/FP32/person-detection-action-recognition-0005.xml
        weights: intel/person-detection-action-recognition-0005/FP32/person-detection-action-recognition-0005.bin
        adapter:
          type: action_detection
          priorbox_out: mbox/priorbox
          loc_out: mbox_loc1/out/conv/flat
          main_conf_out: mbox_main_conf/out/conv/flat/softmax/flat
          add_conf_out_prefix: out/anchor
          add_conf_out_count: 4
          num_action_classes: 3
          detection_threshold: 0.4
          action_confidence_threshold: 0.75
          action_scale: 3

      - framework: dlsdk
        tags:
          - FP16
        model:   intel/person-detection-action-recognition-0005/FP16/person-detection-action-recognition-0005.xml
        weights: intel/person-detection-action-recognition-0005/FP16/person-detection-action-recognition-0005.bin
        adapter:
          type: action_detection
          priorbox_out: mbox/priorbox
          loc_out: mbox_loc1/out/conv/flat
          main_conf_out: mbox_main_conf/out/conv/flat/softmax/flat
          add_conf_out_prefix: out/anchor
          add_conf_out_count: 4
          num_action_classes: 3
          detection_threshold: 0.4
          action_confidence_threshold: 0.75
          action_scale: 3

      - framework: dlsdk
        tags:
          - FP16-INT8
        model:   intel/person-detection-action-recognition-0005/FP16-INT8/person-detection-action-recognition-0005.xml
        weights: intel/person-detection-action-recognition-0005/FP16-INT8/person-detection-action-recognition-0005.bin
        adapter:
          type: action_detection
          priorbox_out: mbox/priorbox
          loc_out: mbox_loc1/out/conv/flat
          main_conf_out: mbox_main_conf/out/conv/flat/softmax/flat
          add_conf_out_prefix: out/anchor
          add_conf_out_count: 4
          num_action_classes: 3
          detection_threshold: 0.4
          action_confidence_threshold: 0.75
          action_scale: 3

    datasets:
      - name: action_detection_dataset_3_classes

        preprocessing:
          - type: resize
            dst_width: 680
            dst_height: 400

        postprocessing:
          - type: soft_nms
            sigma: 0.6
            min_score: 0.4
            keep_top_k: 200
          - type: clip_boxes
            apply_to: prediction
            boxes_normalized: True
          - type: filter
            is_empty: True
            apply_to: prediction
            remove_filtered: True
          - type: normalize_boxes
          - type: clip_boxes
            apply_to: annotation
            boxes_normalized: True

        metrics:
          - type: map
            name: class_agnostic@ap
            ignore_difficult: False
            include_boundaries: False
            allow_multiple_matches_per_ignored: False
            distinct_conf: True
            annotation_source: person_annotation
            prediction_source: class_agnostic_prediction
            label_map: person_label_map

          - type: detection_accuracy
            use_normalization: True
            annotation_source: action_annotation
            prediction_source: action_prediction
            label_map: action_label_map
            ignore_label: 3

global_definitions: ../dataset_definitions.yml
