models:
  - name: person-reidentification-retail-0031

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   intel/person-reidentification-retail-0031/FP32/person-reidentification-retail-0031.xml
        weights: intel/person-reidentification-retail-0031/FP32/person-reidentification-retail-0031.bin
        adapter: reid

      - framework: dlsdk
        tags:
          - FP16
        model:   intel/person-reidentification-retail-0031/FP16/person-reidentification-retail-0031.xml
        weights: intel/person-reidentification-retail-0031/FP16/person-reidentification-retail-0031.bin
        adapter: reid

      - framework: dlsdk
        tags:
          - FP16-INT8
        model:   intel/person-reidentification-retail-0031/FP16-INT8/person-reidentification-retail-0031.xml
        weights: intel/person-reidentification-retail-0031/FP16-INT8/person-reidentification-retail-0031.bin
        adapter: reid

    datasets:
      - name: market1501
        reader: pillow_imread

        preprocessing:
          - type: bgr_to_rgb
          - type: resize
            dst_width: 48
            dst_height: 96
            use_pillow: True
            interpolation: ANTIALIAS

        metrics:
          - name: rank@1
            type: cmc
            top_k: 1

          - type: reid_map

global_definitions: ../dataset_definitions.yml
