models:
  - name: person-reidentification-retail-0079

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   intel/person-reidentification-retail-0079/FP32/person-reidentification-retail-0079.xml
        weights: intel/person-reidentification-retail-0079/FP32/person-reidentification-retail-0079.bin
        adapter: reid

      - framework: dlsdk
        tags:
          - FP16
        model:   intel/person-reidentification-retail-0079/FP16/person-reidentification-retail-0079.xml
        weights: intel/person-reidentification-retail-0079/FP16/person-reidentification-retail-0079.bin
        adapter: reid

      - framework: dlsdk
        tags:
          - INT8
        device: CPU
        model:  intel/person-reidentification-retail-0079/dldt/INT8/person-reidentification-retail-0079.xml
        weights: intel/person-reidentification-retail-0079/0079/dldt/INT8/person-reidentification-retail-0079.bin
        adapter: reid

    datasets:
      - name: market1501
        data_source: Market-1501-v15.09.15
        annotation_conversion:
          converter: market1501_reid
          data_dir: Market-1501-v15.09.15

        preprocessing:
          - type: resize
            dst_width: 64
            dst_height: 160

        metrics:
          - name: rank@1
            type: cmc
            top_k: 1

          - type: reid_map
