models:
  - name: person-attributes-recognition-crossroad-0230

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   intel/person-attributes-recognition-crossroad-0230/FP32/person-attributes-recognition-crossroad-0230.xml
        weights: intel/person-attributes-recognition-crossroad-0230/FP32/person-attributes-recognition-crossroad-0230.bin
        adapter:
          type: person_attributes
          attributes_recognition_out: "453"

      - framework: dlsdk
        tags:
          - FP16
        model:   intel/person-attributes-recognition-crossroad-0230/FP16/person-attributes-recognition-crossroad-0230.xml
        weights: intel/person-attributes-recognition-crossroad-0230/FP16/person-attributes-recognition-crossroad-0230.bin
        adapter:
          type: person_attributes
          attributes_recognition_out: "453"

    datasets:
      - name: person_8_attributes

        preprocessing:
          - type: crop_rect
          - type: resize
            dst_width: 80
            dst_height: 160

        metrics:
          - type: f1-score
            calculate_average: False
            presenter: print_vector

global_definitions: ../dataset_definitions.yml
