models:
  - name: person-detection-0106

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   intel/person-detection-0106/FP32/person-detection-0106.xml
        weights: intel/person-detection-0106/FP32/person-detection-0106.bin
        adapter:
          type: mask_rcnn
          boxes_out: boxes

      - framework: dlsdk
        tags:
          - FP16
        model:   intel/person-detection-0106/FP16/person-detection-0106.xml
        weights: intel/person-detection-0106/FP16/person-detection-0106.bin
        adapter:
          type: mask_rcnn
          boxes_out: boxes

    datasets:
      - name: person_detection

        preprocessing:
          - type: resize
            dst_width: 1344
            dst_height: 800
            aspect_ratio_scale: fit_to_window
          - type: padding
            dst_width: 1344
            dst_height: 800
            pad_type: right_bottom
            use_numpy: True

        postprocessing:
          - type: filter
            apply_to: annotation
            height_range: 100
            aspect_ratio: 0.666, 5
            is_empty: True
            min_visibility: partially occluded
          - type: filter
            apply_to: prediction
            height_range: 100
            is_empty: True
            aspect_ratio: 0.666, 5
          - type: cast_to_int

        metrics:
          - type: map
            ignore_difficult: True
            include_boundaries: True
            allow_multiple_matches_per_ignored: False
            distinct_conf: False

global_definitions: ../dataset_definitions.yml
