models:
  - name: product-detection-0001

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   intel/product-detection-0001/FP32/product-detection-0001.xml
        weights: intel/product-detection-0001/FP32/product-detection-0001.bin
        adapter: ssd

      - framework: dlsdk
        tags:
          - FP16
        model:   intel/product-detection-0001/FP16/product-detection-0001.xml
        weights: intel/product-detection-0001/FP16/product-detection-0001.bin
        adapter: ssd

      - framework: dlsdk
        tags:
          - FP16-INT8
        model:   intel/product-detection-0001/FP16-INT8/product-detection-0001.xml
        weights: intel/product-detection-0001/FP16-INT8/product-detection-0001.bin
        adapter: ssd

    datasets:
      - name: product_detection

        preprocessing:
          - type: resize
            size: 512

        postprocessing:
          - type: resize_prediction_boxes
          - type: cast_to_int
          - type: filter
            min_confidence: 0.02
            apply_to: prediction

global_definitions: ../dataset_definitions.yml
