models:
  - name: resnet50-binary-0001

    launchers:
      - framework: dlsdk
        tags:
          - INT1
        device: CPU
        model:   intel/resnet50-binary-0001/INT1/resnet50-binary-0001.xml
        weights: intel/resnet50-binary-0001/INT1/resnet50-binary-0001.bin
        adapter: classification


    datasets:
      - name: imagenet_1000_classes
        reader: pillow_imread

        preprocessing:
        - type: resize
          size: 256
          aspect_ratio_scale: greater
          use_pillow: True
          interpolation: BILINEAR
        - type: crop
          size: 224
          use_pillow: True
        - type: bgr_to_rgb

        metrics:
          - name: accuracy@top1
            type: accuracy
            top_k: 1
          - name: accuracy@top5
            type: accuracy
            top_k: 5
