models:
  - name: se-resnet-50-cf
    launchers:
      - framework: caffe
        model:   public/se-resnet-50/se-resnet-50.prototxt
        weights: public/se-resnet-50/se-resnet-50.caffemodel
        adapter: classification

    datasets:
      - name: imagenet_1000_classes_2015
        preprocessing:
          - type: resize
            size: 256
          - type: crop
            size: 224
          - type: normalization
            mean: 104, 117, 123

  - name: se-resnet-50
    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   public/se-resnet-50/FP32/se-resnet-50.xml
        weights: public/se-resnet-50/FP32/se-resnet-50.bin
        adapter: classification

      - framework: dlsdk
        tags:
          - FP16
        model:   public/se-resnet-50/FP16/se-resnet-50.xml
        weights: public/se-resnet-50/FP16/se-resnet-50.bin
        adapter: classification

    datasets:
      - name: imagenet_1000_classes_2015
        preprocessing:
          - type: resize
            size: 256
          - type: crop
            size: 224

global_definitions: ../dataset_definitions.yml
