models:
  - name: single-image-super-resolution-1032

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   intel/single-image-super-resolution-1032/FP32/single-image-super-resolution-1032.xml
        weights: intel/single-image-super-resolution-1032/FP32/single-image-super-resolution-1032.bin
        adapter:
          type: super_resolution
          reverse_channels: True
        inputs:
          - name: "0"
            type: INPUT
            value: ".*lr_x4*.png"
          - name: "1"
            type: INPUT
            value: ".*upsample_x4*.png"

      - framework: dlsdk
        tags:
          - FP16
        model:   intel/single-image-super-resolution-1032/FP16/single-image-super-resolution-1032.xml
        weights: intel/single-image-super-resolution-1032/FP16/single-image-super-resolution-1032.bin
        adapter:
          type: super_resolution
          reverse_channels: True
        inputs:
          - name: "0"
            type: INPUT
            value: ".*lr_x4*.png"
          - name: "1"
            type: INPUT
            value: ".*upsample_x4*.png"

      - framework: dlsdk
        tags:
          - FP16-INT8
        model:   intel/single-image-super-resolution-1032/FP16-INT8/single-image-super-resolution-1032.xml
        weights: intel/single-image-super-resolution-1032/FP16-INT8/single-image-super-resolution-1032.bin
        adapter:
          type: super_resolution
          reverse_channels: True
        inputs:
          - name: "0"
            type: INPUT
            value: ".*lr_x4*.png"
          - name: "1"
            type: INPUT
            value: ".*upsample_x4*.png"

    datasets:
      - name: super_resolution_x4

global_definitions: ../dataset_definitions.yml
