models:
  - name: squeezenet1.1-caffe2

    launchers:
      - framework: onnx_runtime
        model: public/squeezenet1.1-caffe2/squeezenet1.1-caffe2.onnx
        adapter: classification

    datasets:
      - name: imagenet_1000_classes
        preprocessing:
          - type: resize
            size: 256
          - type: crop
            size: 227
          - type: normalization
            mean: 103.96,116.78,123.68

  - name: squeezenet1.1-caffe2
    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   public/squeezenet1.1-caffe2/FP32/squeezenet1.1-caffe2.xml
        weights: public/squeezenet1.1-caffe2/FP32/squeezenet1.1-caffe2.bin
        adapter: classification

      - framework: dlsdk
        tags:
          - FP16
        model:   public/squeezenet1.1-caffe2/FP16/squeezenet1.1-caffe2.xml
        weights: public/squeezenet1.1-caffe2/FP16/squeezenet1.1-caffe2.bin
        adapter: classification

      - framework: dlsdk
        tags:
          - FP32-INT8
        model:   public/squeezenet1.1-caffe2/FP32-INT8/squeezenet1.1-caffe2.xml
        weights: public/squeezenet1.1-caffe2/FP32-INT8/squeezenet1.1-caffe2.bin
        adapter: classification

      - framework: dlsdk
        tags:
          - FP16-INT8
        model:   public/squeezenet1.1-caffe2/FP16-INT8/squeezenet1.1-caffe2.xml
        weights: public/squeezenet1.1-caffe2/FP16-INT8/squeezenet1.1-caffe2.bin
        adapter: classification

    datasets:
      - name: imagenet_1000_classes
        preprocessing:
          - type: resize
            size: 256
            aspect_ratio_scale: greater
          - type: crop
            size: 227

global_definitions: ../dataset_definitions.yml
