models:
  - name:  ssd-resnet34-1200-onnx
    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   public/ssd-resnet34-1200-onnx/FP32/ssd-resnet34-1200-onnx.xml
        weights: public/ssd-resnet34-1200-onnx/FP32/ssd-resnet34-1200-onnx.bin
        adapter:
          type: ssd_onnx
          scores_out: '.*scores*'
          labels_out: '.*labels*'
          bboxes_out: '.*bboxes*'


      - framework: dlsdk
        tags:
          - FP16
        model:   public/ssd-resnet34-1200-onnx/FP16/ssd-resnet34-1200-onnx.xml
        weights: public/ssd-resnet34-1200-onnx/FP16/ssd-resnet34-1200-onnx.bin
        adapter:
          type: ssd_onnx
          scores_out: '.*scores*'
          labels_out: '.*labels*'
          bboxes_out: '.*bboxes*'


    datasets:
      - name: ms_coco_detection_80_class_with_background
        preprocessing:
          - type: resize
            size: 1200
            interpolation: LINEAR

        postprocessing:
          - type: resize_prediction_boxes

        metrics:
          - type: coco_precision

global_definitions: ../dataset_definitions.yml
