models:
  - name: text-detection-0003

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   intel/text-detection-0003/FP32/text-detection-0003.xml
        weights: intel/text-detection-0003/FP32/text-detection-0003.bin
        adapter:
          type: pixel_link_text_detection
          pixel_link_out: model/link_logits_/add
          pixel_class_out: model/segm_logits/add
          pixel_class_confidence_threshold: 0.8
          pixel_link_confidence_threshold: 0.8
          min_area: 300
          min_height: 10

      - framework: dlsdk
        tags:
          - FP16
        model:   intel/text-detection-0003/FP16/text-detection-0003.xml
        weights: intel/text-detection-0003/FP16/text-detection-0003.bin
        adapter:
          type: pixel_link_text_detection
          pixel_link_out: model/link_logits_/add
          pixel_class_out: model/segm_logits/add
          pixel_class_confidence_threshold: 0.8
          pixel_link_confidence_threshold: 0.8
          min_area: 300
          min_height: 10

      - framework: dlsdk
        tags:
          - FP16-INT8
        device: CPU
        model:   intel/text-detection-0003/FP16-INT8/text-detection-0003.xml
        weights: intel/text-detection-0003/FP16-INT8/text-detection-0003.bin
        adapter:
          type: pixel_link_text_detection
          pixel_link_out: model/link_logits_/add
          pixel_class_out: model/segm_logits/add
          pixel_class_confidence_threshold: 0.8
          pixel_link_confidence_threshold: 0.8
          min_area: 300
          min_height: 10

    datasets:
      - name: ICDAR2015

        preprocessing:
          - type: resize
            dst_width: 1280
            dst_height: 768

        postprocessing:
          - type: cast_to_int
          - type: filter
            area_range: 300, 980993
            height_range: 10
            width_range: 10
            apply_to: prediction
            remove_filtered: True
          - type: clip_points
            apply_to: prediction

        metrics:
          - type: incidental_text_hmean
            name: f-measure
            ignore_difficult: True

global_definitions: ../dataset_definitions.yml
