models:
  - name: unet-camvid-onnx-0001

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   intel/unet-camvid-onnx-0001/FP32/unet-camvid-onnx-0001.xml
        weights: intel/unet-camvid-onnx-0001/FP32/unet-camvid-onnx-0001.bin
        adapter: segmentation

      - framework: dlsdk
        tags:
          - FP16
        model:   intel/unet-camvid-onnx-0001/FP16/unet-camvid-onnx-0001.xml
        weights: intel/unet-camvid-onnx-0001/FP16/unet-camvid-onnx-0001.bin
        adapter: segmentation

      - framework: dlsdk
        tags:
          - FP16-INT8
        model:   intel/unet-camvid-onnx-0001/FP16-INT8/unet-camvid-onnx-0001.xml
        weights: intel/unet-camvid-onnx-0001/FP16-INT8/unet-camvid-onnx-0001.bin
        adapter: segmentation

    datasets:
      - name: CamVid
        reader: pillow_imread

        preprocessing:
          - type: resize
            dst_height: 368
            dst_width: 480
            use_pillow: True
            interpolation: BILINEAR
          - type: bgr_to_rgb

        postprocessing:
          - type: resize_segmentation_mask
            apply_to: annotation
            dst_height: 368
            dst_width: 480

        metrics:
          - type: mean_iou
            use_argmax: True
            ignore_label: 11
            presenter: print_vector

global_definitions: ../dataset_definitions.yml
