models:
  - name: vehicle-detection-adas-0002

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   intel/vehicle-detection-adas-0002/FP32/vehicle-detection-adas-0002.xml
        weights: intel/vehicle-detection-adas-0002/FP32/vehicle-detection-adas-0002.bin
        adapter: ssd
        cpu_extensions: AUTO

      - framework: dlsdk
        tags:
          - FP16
        model:   intel/vehicle-detection-adas-0002/FP16/vehicle-detection-adas-0002.xml
        weights: intel/vehicle-detection-adas-0002/FP16/vehicle-detection-adas-0002.bin
        adapter: ssd
        cpu_extensions: AUTO

      - framework: dlsdk
        tags:
          - INT8
        model:   intel/vehicle-detection-adas-0002/INT8/vehicle-detection-adas-0002.xml
        weights: intel/vehicle-detection-adas-0002/INT8/vehicle-detection-adas-0002.bin
        adapter: ssd
        cpu_extensions: AUTO

    datasets:
      - name: vehicle_detection_dataset

        preprocessing:
          - type: resize
            dst_width: 672
            dst_height: 384

        postprocessing:
          - type: resize_prediction_boxes
          - type: cast_to_int
          - type: filter
            apply_to: annotation
            height_range: 30
            is_empty: True

        metrics:
          - type: map
            integral: 11point
            ignore_difficult: True
            include_boundaries: True
            allow_multiple_matches_per_ignored: True
            use_filtered_tp: True
