models:
  - name: vehicle-license-plate-detection-barrier-0106

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   intel/vehicle-license-plate-detection-barrier-0106/FP32/vehicle-license-plate-detection-barrier-0106.xml
        weights: intel/vehicle-license-plate-detection-barrier-0106/FP32/vehicle-license-plate-detection-barrier-0106.bin
        adapter: ssd

      - framework: dlsdk
        tags:
          - FP16
        model:   intel/vehicle-license-plate-detection-barrier-0106/FP16/vehicle-license-plate-detection-barrier-0106.xml
        weights: intel/vehicle-license-plate-detection-barrier-0106/FP16/vehicle-license-plate-detection-barrier-0106.bin
        adapter: ssd

      - framework: dlsdk
        tags:
          - FP16-INT8
        model:   intel/vehicle-license-plate-detection-barrier-0106/FP16-INT8/vehicle-license-plate-detection-barrier-0106.xml
        weights: intel/vehicle-license-plate-detection-barrier-0106/FP16-INT8/vehicle-license-plate-detection-barrier-0106.bin
        adapter: ssd

    datasets:
      - name: vehicle_license_plate_detection

        preprocessing:
          - type: resize
            dst_width: 300
            dst_height: 300

        postprocessing:
          - type: clip_boxes
            apply_to: prediction
            dst_width: 1
            dst_height: 1
          - type: resize_prediction_boxes
          - type: filter
            apply_to: prediction
            min_confidence: 0.005
            is_empty: True
          - type: filter
            apply_to: annotation
            area_ratio: 0.034722222222222224

        metrics:
          - type: map
            ignore_difficult: True
            include_boundaries: False
            allow_multiple_matches_per_ignored: True
            distinct_conf: False
            presenter: print_vector

global_definitions: ../dataset_definitions.yml
