models:
  - name: vehicle-detection-adas-binary-0001

    launchers:
      - framework: dlsdk
        tags:
          - FP32-INT1
        model:   intel/vehicle-detection-adas-binary-0001/FP32-INT1/vehicle-detection-adas-binary-0001.xml
        weights: intel/vehicle-detection-adas-binary-0001/FP32-INT1/vehicle-detection-adas-binary-0001.bin
        adapter: ssd

    datasets:
      - name: vehicle_detection_dataset

        preprocessing:
          - type: resize
            dst_width: 672
            dst_height: 384

        postprocessing:
          - type: resize_prediction_boxes
          - type: cast_to_int
          - type: filter
            apply_to: annotation
            height_range: 30
            is_empty: True

        metrics:
          - type: map
            integral: 11point
            ignore_difficult: True
            include_boundaries: True
            allow_multiple_matches_per_ignored: True
            use_filtered_tp: True

global_definitions: ../dataset_definitions.yml
