models:
  - name: vgg16-cf
    launchers:
      - framework: caffe
        model:   public/vgg16/vgg16.prototxt
        weights: public/vgg16/vgg16.caffemodel
        adapter: classification
    datasets:
      - name: imagenet_1000_classes
        preprocessing:
          - type: resize
            size: 256
            aspect_ratio_scale: greater
          - type: crop
            size: 224
          - type: normalization
            mean: 103.939, 116.779, 123.68

  - name: vgg16
    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   public/vgg16/FP32/vgg16.xml
        weights: public/vgg16/FP32/vgg16.bin
        adapter: classification

      - framework: dlsdk
        tags:
          - FP16
        model:   public/vgg16/FP16/vgg16.xml
        weights: public/vgg16/FP16/vgg16.bin
        adapter: classification

      - framework: dlsdk
        tags:
          - FP32-INT8
        model:   public/vgg16/FP32-INT8/vgg16.xml
        weights: public/vgg16/FP32-INT8/vgg16.bin
        adapter: classification

      - framework: dlsdk
        tags:
          - FP16-INT8
        model:   public/vgg16/FP16-INT8/vgg16.xml
        weights: public/vgg16/FP16-INT8/vgg16.bin
        adapter: classification

    datasets:
      - name: imagenet_1000_classes
        preprocessing:
          - type: resize
            size: 256
            aspect_ratio_scale: greater
          - type: crop
            size: 224

global_definitions: ../dataset_definitions.yml
