models:
  - name: vgg19-cf
    launchers:
      - framework: caffe
        model:   public/vgg19/vgg19.prototxt
        weights: public/vgg19/vgg19.caffemodel
        adapter: classification
    datasets:
      - name: imagenet_1000_classes
        preprocessing:
          - type: resize
            size: 256
            aspect_ratio_scale: greater
          - type: crop
            size: 224
          - type: normalization
            mean: 103.939, 116.779, 123.68

  - name: vgg19
    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   public/vgg19/FP32/vgg19.xml
        weights: public/vgg19/FP32/vgg19.bin
        adapter: classification

      - framework: dlsdk
        tags:
          - FP16
        model:   public/vgg19/FP16/vgg19.xml
        weights: public/vgg19/FP16/vgg19.bin
        adapter: classification

    datasets:
      - name: imagenet_1000_classes
        preprocessing:
          - type: resize
            size: 256
            aspect_ratio_scale: greater
          - type: crop
            size: 224
