models:

  - name: vgg19-caffe2
    launchers:
      - framework: onnx_runtime
        model: public/vgg19-caffe2/vgg19-caffe2.onnx
        adapter: classification

    datasets:
      - name: imagenet_1000_classes
        preprocessing:
          - type: resize
            size: 256
            aspect_ratio_scale: greater
          - type: crop
            size: 224
          - type: normalization
            mean: 103.939, 116.779, 123.68

  - name: vgg19-caffe2
    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   public/vgg19-caffe2/FP32/vgg19-caffe2.xml
        weights: public/vgg19-caffe2/FP32/vgg19-caffe2.bin
        adapter: classification

      - framework: dlsdk
        tags:
          - FP16
        model:   public/vgg19-caffe2/FP16/vgg19-caffe2.xml
        weights: public/vgg19-caffe2/FP16/vgg19-caffe2.bin
        adapter: classification

    datasets:
      - name: imagenet_1000_classes
        preprocessing:
          - type: resize
            size: 256
            aspect_ratio_scale: greater
          - type: crop
            size: 224

global_definitions: ../dataset_definitions.yml
