models:
  - name: weld-porosity-detection-0001
    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   intel/weld-porosity-detection-0001/FP32/weld-porosity-detection-0001.xml
        weights: intel/weld-porosity-detection-0001/FP32/weld-porosity-detection-0001.bin
        adapter: classification

      - framework: dlsdk
        tags:
          - FP16
        model:   intel/weld-porosity-detection-0001/FP16/weld-porosity-detection-0001.xml
        weights: intel/weld-porosity-detection-0001/FP16/weld-porosity-detection-0001.bin
        adapter: classification

    datasets:
      - name: weld-porosity
        reader:
          type: opencv_imread
          multi_infer: True

        preprocessing:
          - type: resize
            size: 224
            aspect_ratio_scale: greater
          - type: crop
            size: 224

        metrics:
          - type: accuracy

global_definitions: ../dataset_definitions.yml
