models:
  - name: yolo-v1-tiny-tf

    launchers:
      - framework: tf
        tags:
          - FP32
        model: public/yolo-v1-tiny-tf/yolo-v1-tiny.pb
        inputs:
          - name: 'input_1'
            type: INPUT
            shape: 1,416,416,3
        output_names: [conv2d_9/BiasAdd]
        adapter:
          type: yolo_v2
          anchors: "1.08,1.19, 3.42,4.41, 6.63,11.38, 9.42,5.11, 16.62,10.52"
          num: 5
          coords: 4
          classes: 20
          raw_output: True

    datasets:
      - name: VOC2012_without_background

        preprocessing:
          - type: bgr_to_rgb
          - type: normalization
            std: 255

          - type: resize
            size: 416

        postprocessing:
          - type: resize_prediction_boxes
          - type: filter
            apply_to: prediction
            min_confidence: 0.001
            remove_filtered: True
          - type: nms
            overlap: 0.5
          - type: clip_boxes
            apply_to: prediction

        metrics:
          - type: map
            integral: 11point
            ignore_difficult: true
            presenter: print_scalar

  - name: yolo-v1-tiny-tf

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   public/yolo-v1-tiny-tf/FP32/yolo-v1-tiny-tf.xml
        weights: public/yolo-v1-tiny-tf/FP32/yolo-v1-tiny-tf.bin
        adapter:
          type: yolo_v2
          anchors: "1.08,1.19, 3.42,4.41, 6.63,11.38, 9.42,5.11, 16.62,10.52"
          num: 5
          coords: 4
          classes: 20

      - framework: dlsdk
        tags:
          - FP16
        model:   public/yolo-v1-tiny-tf/FP16/yolo-v1-tiny-tf.xml
        weights: public/yolo-v1-tiny-tf/FP16/yolo-v1-tiny-tf.bin
        adapter:
          type: yolo_v2
          anchors: "1.08,1.19, 3.42,4.41, 6.63,11.38, 9.42,5.11, 16.62,10.52"
          num: 5
          coords: 4
          classes: 20

    datasets:
      - name: VOC2012_without_background

        preprocessing:
          - type: resize
            size: 416

        postprocessing:
          - type: resize_prediction_boxes
          - type: filter
            apply_to: prediction
            min_confidence: 0.001
            remove_filtered: True
          - type: nms
            overlap: 0.5
          - type: clip_boxes
            apply_to: prediction

        metrics:
          - type: map
            integral: 11point
            ignore_difficult: true
            presenter: print_scalar

global_definitions: ../dataset_definitions.yml
