models:
  - name: yolo-v2-tiny-vehicle-detection-0001
    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model: intel/yolo-v2-tiny-vehicle-detection-0001/FP32/yolo-v2-tiny-vehicle-detection-0001.xml
        weights: intel/yolo-v2-tiny-vehicle-detection-0001/FP32/yolo-v2-tiny-vehicle-detection-0001.bin
        adapter:
          type: yolo_v2
          anchors: "0.57273, 0.677385, 1.87446, 2.06253, 3.33843, 5.47434, 7.88282, 3.52778, 9.77052, 9.16828"
          num: 5
          coords: 4
          classes: 80

      - framework: dlsdk
        tags:
          - FP16
        model: intel/yolo-v2-tiny-vehicle-detection-0001/FP16/yolo-v2-tiny-vehicle-detection-0001.xml
        weights: intel/yolo-v2-tiny-vehicle-detection-0001/FP16/yolo-v2-tiny-vehicle-detection-0001.bin
        adapter:
          type: yolo_v2
          anchors: "0.57273, 0.677385, 1.87446, 2.06253, 3.33843, 5.47434, 7.88282, 3.52778, 9.77052, 9.16828"
          num: 5
          coords: 4
          classes: 80

      - framework: dlsdk
        tags:
          - FP16-INT8
        model: intel/yolo-v2-tiny-vehicle-detection-0001/FP16-INT8/yolo-v2-tiny-vehicle-detection-0001.xml
        weights: intel/yolo-v2-tiny-vehicle-detection-0001/FP16-INT8/yolo-v2-tiny-vehicle-detection-0001.bin
        adapter:
          type: yolo_v2
          anchors: "0.57273, 0.677385, 1.87446, 2.06253, 3.33843, 5.47434, 7.88282, 3.52778, 9.77052, 9.16828"
          num: 5
          coords: 4
          classes: 80

    datasets:
      - name: barrier_vehicle_detection_dataset_index_class_2

        preprocessing:
          - type: resize
            size: 416
        postprocessing:
          - type: resize_prediction_boxes
          - type: filter
            apply_to: prediction
            min_confidence: 0.001
            remove_filtered: true
          - type: nms
            overlap: 0.5
          - type: clip_boxes
            apply_to: prediction
        metrics:
          - type: map
            integral: 11point
            ignore_difficult: false
            presenter: print_scalar
          - type: coco_precision
            max_detections: 100
            threshold: 0.5

global_definitions: ../dataset_definitions.yml
