models:
  - name: yolo-v2-tiny-tf

    launchers:
      - framework: tf
        tags:
          - FP32
        model:   public/yolo-v2-tiny-tf/yolo-v2-tiny.pb
        adapter:
          type: yolo_v2
          anchors: "0.57273, 0.677385, 1.87446, 2.06253, 3.33843, 5.47434, 7.88282, 3.52778, 9.77052, 9.16828"
          num: 5
          coords: 4
          classes: 80
          raw_output: True

    datasets:
      - name: ms_coco_detection_80_class_without_background

        preprocessing:
          - type: bgr_to_rgb
          - type: normalization
            std: 255.0
          - type: resize
            size: 416

        postprocessing:
          - type: resize_prediction_boxes
          - type: filter
            apply_to: prediction
            min_confidence: 0.001
            remove_filtered: True
          - type: nms
            overlap: 0.5
          - type: clip_boxes
            apply_to: prediction

        metrics:
          - type: map
            integral: 11point
            ignore_difficult: False
            presenter: print_scalar
          - type: coco_precision
            max_detections: 100
            threshold: 0.5

  - name: yolo-v2-tiny-tf

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   public/yolo-v2-tiny-tf/FP32/yolo-v2-tiny-tf.xml
        weights: public/yolo-v2-tiny-tf/FP32/yolo-v2-tiny-tf.bin
        adapter:
          type: yolo_v2
          anchors: "0.57273, 0.677385, 1.87446, 2.06253, 3.33843, 5.47434, 7.88282, 3.52778, 9.77052, 9.16828"
          num: 5
          coords: 4
          classes: 80

      - framework: dlsdk
        tags:
          - FP16
        model:   public/yolo-v2-tiny-tf/FP16/yolo-v2-tiny-tf.xml
        weights: public/yolo-v2-tiny-tf/FP16/yolo-v2-tiny-tf.bin
        adapter:
          type: yolo_v2
          anchors: "0.57273, 0.677385, 1.87446, 2.06253, 3.33843, 5.47434, 7.88282, 3.52778, 9.77052, 9.16828"
          num: 5
          coords: 4
          classes: 80

    datasets:
      - name: ms_coco_detection_80_class_without_background

        preprocessing:
          - type: resize
            size: 416

        postprocessing:
          - type: resize_prediction_boxes
          - type: filter
            apply_to: prediction
            min_confidence: 0.001
            remove_filtered: True
          - type: nms
            overlap: 0.5
          - type: clip_boxes
            apply_to: prediction

        metrics:
          - type: map
            integral: 11point
            ignore_difficult: False
            presenter: print_scalar
          - type: coco_precision
            max_detections: 100
            threshold: 0.5

global_definitions: ../dataset_definitions.yml
